### ISSUE TITLE
more comments/logic around voting initiative valuation

### ISSUE THREAD

**Issue by docrostov** [loathers/garbage-collector#1147]
this is more readable. good job. my one thing here would be that the actual list of valuations is kind of mediocre but it's fine; a few comments explaining would be nice. in particular, i think you could make a justification that famxp is a bit higher because it helps with goose leveling for the 50k meat skill.

_Originally posted by @docrostov in https://github.com/Loathing-Associates-Scripting-Society/garbage-collector/pull/1143#discussion_r989366806_

we should justify these in comments to make sure people know why we value things as we do

**Comment by horrible-little-slime** [comment]
@JamesDowney or @Pantocyclus would be good for handling this

**Comment by docrostov** [comment]
finally closing this with my "one goddamn comment" branch
