### ISSUE TITLE
ability for garbo to evaluate embezzler value vs witchess knights

### ISSUE THREAD

**Issue by docrostov** [loathers/garbage-collector#1159]
there was a very interesting convo in the ASS discord last night. 

https://discord.com/channels/466605739838930955/534709227260870656/1031795068094390314

TLDR: for a good bunch of users, it's actually actively better to copy some quantity of witchess knights -instead- of embezzlers. this is not true if they only drop one horseradish, but if you have high familiar XP on, you can goose-dupe the horseradishes. and that ends up turning the value of a free witchess fight vs embezzler into embezzler meat versus 2x horseradish + VOA (since you retain the turn for a normal barf combat). that's... like, a pretty wild amount of value. and because they're free, it's not even -that- hard to get your goose to a point where it's generating 1 drone per combat. 

i don't necessarily think we need to support this immediately, or at all. but this feels like purely positive value for users that we should consider whenever we refactor embezzler valuation & how to use our start-of-day copiers.

**Comment by docrostov** [comment]
i also think, incidentally, this is case of something where it is essentially impossible to oversaturate the horseradish market. even on a zero-embezzler account, the buff from horseradish is worth >6k meat per horseradish in barf mountain; that establishes a pretty high price floor if you consider that 6k x2 + voa is likely 15-18k on almost every account. when horseradishes are below 6k, something is terribly wrong and garbo will end up buying them out to eat, increasing demand. a funny case of garbo feeding garbo.

**Comment by horrible-little-slime** [comment]
Keep in mind that horseradishes need to compete with other food items; being an extremely good deal isn't alone enough to guarantee it's worth using, unlike, say, potions.

One thing to keep in mind about gooso is that, while the fights are free and thus maintaining the +10 famexp is trivial, you are sacrificing the value of drops familiars. It's definitely going to win, but that also means that it's not just 2x horseradish compared to other free fights. There's an opportunity cost there.

**Comment by docrostov** [comment]
OUT OF FUCKIN SCOPE
