### ISSUE TITLE
Exclude items in closet from final profit calculation

### ISSUE THREAD

**Issue by eegeeZA** [loathers/garbage-collector#1289]
Garbo should not include items 'added' by retrieving from closet in the final profit calculations. I am not sure about the negative profit, but I assume that part if fine.

![image](https://user-images.githubusercontent.com/2684652/218244449-092c176d-3598-4279-b283-3aa56ea594ac.png)

**Comment by s-k-z** [comment]
The data relies on KoLmafia's `mySessionResults()` function. That one might be sensible to change to not include items moved from closet to inventory.

Otherwise, the only thing the script can sensibly do is to put the items back into the closet before it is done.

**Comment by eegeeZA** [comment]
Cool, that makes sense. I see session results do show additions for items removed from the closet, and show negatives if items are moved to the closet. I tried now during a run to 'zero out entries' on the interface and it reflected correctly on mafia's session.

I'm fond of the idea for Garbo to return items to the closet. That's currently what I do anyway after the run.
