### ISSUE TITLE
For Pig Skinner with Pointer Finger Ring, prefer MSG to Carrot for Latte

### ISSUE THREAD

**Issue by Ignose** [loathers/garbage-collector#1314]
Bag of Park Garbage = 200 meat - 15% chance. 20% Item Find from Latte (Carrot) is therefore ~6 MPA.
Mafia Pointer Finger + Head in the Game = 65% crit chance. +15% Crit Chance from MSG raises this to 80%. Assuming each crit is worth ~500 meat, an extra 15% chance is worth 75 MPA - net benefit of 69 (nice) MPA.

When Crit Source is Head in the Game and Garbo configures Latte, Garbo should therefore prefer MSG to Carrot.

**Comment by uthuluc** [comment]
Remember to factor in the base 9% crit chance. Base + HitG + MPF + latte = 89%.
Consider adding black body spray (300 meat for 10 turns of +10%) = 99% chance of meat crit.

**Comment by Malibu-Stacey** [comment]
I tested this & it worked.
