### ISSUE TITLE
Wanderer Zone handling expansion

### ISSUE THREAD

**Issue by Shiverwarp** [loathers/garbage-collector#1318]
Related to currently in progress PR here: #1313 

It's possible that certain zones will still be profitable even if we cannot guarantee 100% combat rate (This is also another option, of actually buffing +combat) or that zones require certain extra handling to be valid wander locations.

The Rifts with the closed circuit phone are another interesting prospect, because the bosses are free, if we yellow ray enough monsters, we get an extra free fight with a boss that drops 2x shadow items

**Locations that we may also consider for long aftercore (or if there is some way to know whether we have already encountered one-time adventures this ascension):**
- The Sleazy Back Alley
- The Haunted Pantry
- The Outskirts of Cobb's Knob 

**Locations we may consider with additional handling:**
- Madness Bakery (Only if you have enough ingredients to make popular tarts, have done the quest, and creating popular tarts is meat positive)
- The Haunted Billiards Room (Only safe if you already have a pool cue. Possibly unsafe if stolen via pvp etc)

**Locations that may still be profitable to wander in despite NCs (Demon name superlikelies that are 1/150 chance)**
- The Haunted Bathroom 
- The Spooky Forest
- Pandamonium Slums (Also has a one-time adventure)

**Comment by horrible-little-slime** [comment]
Rift bosses are going to have to be a bit of a conversation; we can't assume that arbitrary accounts can beat them without spending nontrivial resources. It might be worth recycling/renaming the fightGlitch flag to something like `garbo_canSurviveToughFights` or something less obtuse than that

**Comment by Shiverwarp** [comment]
It may even have to be more bespoke than the glitch fight because the bosses have such specific gimmicks (Extremely high damage based on max HP, spell reflection, complete attack immunity, etc)

**Comment by docrostov** [comment]
closing this because i think this is too broad and the amount of combat handling needed to make garbo do the rift bosses is too much, and actually building the valuation engine for the turn-spent NCs is... a lot. shiver, please feel free to re-make this issue or make PRs addressing these, i just think this is too wide-spanning for one issue.
