### ISSUE TITLE
loathers migration for garbo

### ISSUE THREAD

**Issue by docrostov** [loathers/garbage-collector#1383]
now that i am all married and shit, i am going to be a bit more of a stickler about migrating stuff to loathers. sam and i would like to do the opencollective thing, but to do that, we need to have all of our projects in one place... especially our projects that are the most active. i know, it is a sad time, but it must be so. i am going to put a 1-2 week allowance on here but i want us to migrate garbo within the next two weeks. here are things that i would like to accompany this, but i can certainly be persuaded otherwise:

- draft a kolmafia.us thread for the script that we can post when we migrate (i know phred disagrees, i am fine with not, but i want to at least raise it as a thing because i remain convinced it is good/ok to share our work)
- create an issues template (and delete/complete some of the old issues that are stale and either handled or almost handled)
- revise the garbo documentation a little bit to add clarity in certain spots
- test behavior for the various forms of install on a junk/outdated LASS repo, migrate the junk/outdated LASS repo, and get a feel for what kind of errors might manifest from the migration
- phred and i go through all repo settings the day we migrate and make sure everything makes sense

again, we do not need to do all of these immediately, and i know phred explicitly does not want us to do #1. but i do want to at least bring it up as a "hey, let's discuss this" kind of thing and get these done in the next few weeks.

**Comment by horrible-little-slime** [comment]
I have no particular objection to having a kolmafia.us post other than not wanting to personally maintain it. My objection is, and has been, to being in the script manager, because I think we shouldn't encourage people to install garbo without reading the readme.
