### ISSUE TITLE
Use volcano disco for sobriety instead of free volcoino, when MPA is very high

### ISSUE THREAD

**Issue by sundayLOOKplants** [loathers/garbage-collector#1490]
when cognac-ing, etc, the turns from a splendid martini (etc) are worth a fair bit more than 1 volcoino.

**Comment by docrostov** [comment]
garbo already shuts off at VOA > 10k; if you want this functionality, it's relatively easy to do a quick ash wrapper that `drink 1 splendid martini; [insert whatever command is needed to then clear that with volcano]` before you run garbo. closing this.
