### ISSUE TITLE
Offhand equips during free fights

### ISSUE THREAD

**Issue by Fawoosh** [loathers/garbage-collector#1533]
Had Shield of the Skeleton Lord equipped for the entirety of my free fight section, but wouldn't something like sneebgleeb or can of mixed everything be better in this situation? Or even latte? It was fishing for marginal fam drops so I do not believe the famwt was contributing to anything.

**Comment by docrostov** [comment]
do you have a log you can share? it might have info about the maximizer strings/reads it was doing to get to that. i agree, that seems weird, would love to see if there's just a malformed call or something in there.

**Comment by horrible-little-slime** [comment]
> do you have a log you can share? it might have info about the maximizer strings/reads it was doing to get to that. i agree, that seems weird, would love to see if there's just a malformed call or something in there.

nope, nothing weird or malformed, we just don't have any code that values gleeb or come

**Comment by Fawoosh** [comment]
[Butts_McGruff_20231009.txt](https://github.com/loathers/garbage-collector/files/12862028/Butts_McGruff_20231009.txt)

Here's that session log
