### ISSUE TITLE
[BUG] Still experiencing infinite Executing Barf Turn/Thesis loop, even when owning a pocket prof.

### ISSUE THREAD

**Issue by paniclord** [loathers/garbage-collector#1623]
**Before Reporting**
Ensure that KoLMafia and garbo are both up to date before reporting a bug. If you have installed mafia in a weird or non-standard way, let us know any details about that here. But also, if you've installed mafia in a weird or non-standard way, I'm telling you right now that that's your bug. Also, check existing github issues to see if this has already been reported. If it has, consider leaving a comment with any additional information you can give on _that_ issue, instead of making a new one.

Also, read [this](BUGS.md).

**Describe the bug**
Experiencing the Executing Barf Turn/Thesis infinite loop, even after updating both mafia and garbo. I own a pocket professor. 

**To Reproduce**
run garbo 

**Expected behavior**
garbo successfully runs and completes without the infinite loop

**Session Log**
Attach a full KoLMafia session log from the day you encount
ered the bug. Include details about when in the log the bug occurred to help developers rapidly find the error. Copy and paste any associated red text printed to the gCLI during this error.
[panic_lord_20231011.txt](https://github.com/loathers/garbage-collector/files/12867171/panic_lord_20231011.txt)

**Additional context**
Suddenly started happening as of 1 or 2 days ago.

**Comment by paniclord** [comment]
I think this may be a Mafia bug rather than a garbo bug, as I think _thesisDelivered gets changed earlier in the day but isn't properly set.

**Comment by pstalcup** [comment]
https://github.com/loathers/garbage-collector/pull/1624

This may be a mafia bug, but we can still prevent the infinite loop.
