### ISSUE TITLE
[FEATURE]Opportunity to use Free Candy map, when profitable

### ISSUE THREAD

**Issue by Ignose** [loathers/garbage-collector#1627]
Check price of Free Candy, check Available Outfits, check value of Expected Candy of available Outfits. If value of candy > value of map, use a free candy map for free candy.

If this is too item farmy for Garbo, that's also fine.

**Comment by Malibu-Stacey** [comment]
https://loathers.github.io/PR-Overview.html

**Comment by horrible-little-slime** [comment]
I agree that we should close this issue, but not necessarily in a "PRs welcome" way (although PRs are for sure welcome!)

The issue template currently says the following
> If that piece of content came out extremely recently (e.g., this month), you almost certainly shouldn't file this feature request unless the next section is going to be extremely, extremely detailed--we're probably working on it!
This is unfortunately just not enough detail for us to go on. We currently are planning to implement the map, although probably not by calling free candy. First, though, we need to grimoirize our free fights, or we'll create this infrastructure only to not use it, and then have to create it all over again.


Some ways this could have been more detailed is:
- more precise valuation of the map
- discussion of outfit code, both for combat and out of combat--is it sustainable for garbo to start expecting a lot of people to have one of those old halloween masks? `mallPrice` is unreliable, should we let people choose their outfit with a pref, or will garbo _make_ mallPrice reliable by flooding the market with overpriced candies?
- Challenges that this in particular might set up. In this case, contrasting it with freecandy, I actually see the opposite--we don't need to have any infrastructure for changing blocks and we don't need to spend as much code making sure we do it in as few server requests as humanly possible. We're running an extremely bounded number of encounters and that makes our life a lot easier
- idk probably other stuff.

This is a feature we plan to add, but if you're going to make a feature request for a piece of recent content, please try to include more detail so it can be constructive.

For older content, more detail is less important, but it's still good to include more information so we can turn this into a feature.

**Comment by Ignose** [comment]
Would you prefer:
1) These be more fleshed out only,
2) These go into discussions, under ideas
3) Both

Obviously, submitting a PR being ideal.

**Comment by horrible-little-slime** [comment]
I think for something that isn't in the "this isn't a feature, but mostly because it is new" territory, probably option 1.

Discussions might be a neat place for recent content.
