### ISSUE TITLE
[BUG] TURNS argument is ignored

### ISSUE THREAD

**Issue by fknslacker** [loathers/garbage-collector#1632]
**Describe the bug**
For the past 2-3 days garbo has been adventuring until 0 advs are left, when called with both "garbo ascend turns=-5" and "garbo turns=-50"

**To Reproduce**

1. Via the cli run "garbo ascend turns=-5"

**Expected behavior**
garbo to finish with 5 adventures remaining

**Session Log**
Attach a full KoLMafia session log from the day you encountered the bug. Include details about when in the log the bug occurred to help developers rapidly find the error. Copy and paste any associated red text printed to the gCLI during this error.

[fknslacker_20231011.txt](https://github.com/loathers/garbage-collector/files/12876564/fknslacker_20231011.txt)

**Additional context**
1. Only appeared in the past ~week

**Comment by pstalcup** [comment]
This should be resolved. Please let us know if you have persistent issues.
