### ISSUE TITLE
[BUG] Garbo Relay browser is blank

### ISSUE THREAD

**Issue by whatisbecome1111** [loathers/garbage-collector#1633]
Tested on Version 27640 and 27645 of kolmafia.
Tested both versions on Windows 10 and Linux
Chrome/firefox for windows and midori for linux

Relay option dropdown doesn't load Garbo interface, it is completely blank; the character sheet, top bar and chat bar all remain fine.

Go to http://127.0.0.1:60080/game.php 
click on -run script-
Select garbo
See nothing

Garbo preferences should show up.

I include a trace and session log.
[multiclanleader_20231012.txt](https://github.com/loathers/garbage-collector/files/12878397/multiclanleader_20231012.txt)
[TRACE_20231012.txt](https://github.com/loathers/garbage-collector/files/12878399/TRACE_20231012.txt)

**Comment by Tokoeka** [comment]
Have tested in r27646 in firefox on windows 10: the web interface for garbo did show up.

**Comment by horrible-little-slime** [comment]
@Tokoeka I'm going to guess this means you're on an old version of the relay, probably due to the recent changes in the way our build works and our file structures. I'm also in firefox and hitting the issue. We're workin' on it

**Comment by whatisbecome1111** [comment]
@horrible-little-slime  Thanks, just in case helps: I un-installed garbo while on 27640 and then I downloaded 27646 and installed garbo about 5/10 minutes ago. I now see the "Interrupt Garbo" and "Save Changes" button but nothing else.
[multiclanleader_20231012.txt](https://github.com/loathers/garbage-collector/files/12884842/multiclanleader_20231012.txt)
[TRACE_20231012.txt](https://github.com/loathers/garbage-collector/files/12884843/TRACE_20231012.txt)

**Comment by horrible-little-slime** [comment]
The very most recent version should fix that, but let us know if it doesn't

**Comment by whatisbecome1111** [comment]
@horrible-little-slime I am actually now back to the completely white page. I un-installed garbo, closed Mafia and then installed garbo just now. Tried on windows 10 with Chrome, Firefox. Did a hard refresh of the browser to clear any caching issues. What version of Mafia were you using, 27646?

**Comment by gausie** [comment]
It's not a mafia issue. Could you send the HTML for your blank page? RIght click and hit view source. Thanks!

**Comment by gausie** [comment]
Oh I've worked it out. One moment

**Comment by gausie** [comment]
Should be fixed now. As always, comment again if it isn't.
