### ISSUE TITLE
[BUG] Drunkula's wineglass not equipped while going for "Non Barf Turn/Daily Dungeon (drunk)"

### ISSUE THREAD

**Issue by ktpolanski** [loathers/garbage-collector#1668]
**Describe the bug**
I tabbed into Mafia to see a wall of
```
Executing Non Barf Turn/Daily Dungeon (drunk)

You are too drunk to continue.
```

Inspecting my outfit revealed no Drunkula's wineglass equipped. I tried to manually adventure in the Daily Dungeon without the wineglass equipped and got sent into a drunken stupor, so Mafia's fail-safe seems to be right here.

**To Reproduce**
Presumably run `garbo ascend` while overdrunk?

**Expected behavior**
Put on the wineglass and waltz through safely.

**Session Log**
[DanceCommander6_20231021.txt](https://github.com/loathers/garbage-collector/files/13061756/DanceCommander6_20231021.txt)
I did the Daily Dungeon manually at the end there.

**Comment by pstalcup** [comment]
Oops. I'll get to this in a bit. Sorry about that
