### ISSUE TITLE
[BUG] Monkey paw wish valueation

### ISSUE THREAD

**Issue by Aliisza** [loathers/garbage-collector#1681]
**Describe the bug**
On breakfast leg when acquiring the 5 paw wishes garbo went for 2x braaains, 2x sinuses for miles, and 1x lets go shopping. Instead of using Frosty at all in place of any of the existing wishes. 

**To Reproduce**

**Expected behavior**

Would think it would favor a 200% effect over a 150% one. 

**Session Log**
Attach a full KoLMafia session log from the day you encountered the bug. Include details about when in the log the bug occurred to help developers rapidly find the error. Copy and paste any associated red text printed to the gCLI during this error.

Happens quite early in the log. I searched for "pawwish" to find it.

**Additional context**
Add any other context about the problem here. Does this always happen post-loop, but never pre-loop? Did this start happening when you got some particular IotM?
[aliisza_20231023.txt](https://github.com/loathers/garbage-collector/files/13078200/aliisza_20231023.txt)

**Comment by horrible-little-slime** [comment]
Let's Go Shopping is available from the sorority brain in 20-turn increments, which costs about 70k. So it costs 3.5k a turn to get via the regular potion.
Frosty is available from the frost flower in 50-turn increments, which costs 165k. So it costs 3.3k a turn to get via the regular potion--a remarkably similar cost

When we doubled Frosty with the pillkeeper, we were doubling a longer buff (that is, getting more mileage out of our doubler) and making sure we get a high-value buff to cover the entire stint of Embezzlers (with 17 overage turns). That seems like a pretty sensible choice to me!

Once you have 100 turns of Frosty, there's no reason to spend a paw wish on it.
