### ISSUE TITLE
[FEATURE] Return clan stash items when rollover's fast approaching

### ISSUE THREAD

**Issue by Alium58** [loathers/garbage-collector#1688]
**Is your feature request related to a problem? Please describe.**
Yesterday garbo was happily bashing tourists when RO hit. Bad news is I had my clan's pantsgiving equipped. Didn't realize until now, which is almost the following RO. Its a feels bad man situation where I have had the pants all day, depriving my clan friends from enjoying it.

No doubt this is my fault for running garbo too close to RO. I'm confident it will happen to me again in the future though

**Describe the solution you'd like**
X minutes prior to RO, return all clan stash items. There was a somewhat similar change to autoscend in this PR where bedtime is done 5 mins prior to RO
https://github.com/loathers/autoscend/pull/1292

Perhaps also enable the `quick` flag to get through as many advs as possible before RO

**Comment by Rinn** [comment]
if we make the garbo quests check `ready: canContinue` by default we could just make that check time to rollover like autoscend and that should cover this yah?
