### ISSUE TITLE
Not using Fire Extinguisher charges or replica batoomerang 

### ISSUE THREAD

**Issue by Fawoosh** [loathers/garbage-collector#1699]
I am finding that these two resources are being unused in my second leg of garbo after CS.

I have also noticed that my extinguisher charges do not get used in leg 1 either.

**Comment by Fawoosh** [comment]
[Butts_McGruff_20231029.txt](https://github.com/loathers/garbage-collector/files/13198997/Butts_McGruff_20231029.txt)

**Comment by Tapionator** [comment]
These work for me but the only differing factor between myself and Fawoosh is that I have Stomping Boots and he does not. It may be an issue with the "// Fire Extinguisher on best available target" section of Garbo.

**Comment by Fawoosh** [comment]
[Butts_McGruff_20231112.txt](https://github.com/loathers/garbage-collector/files/13328139/Butts_McGruff_20231112.txt)

**Comment by Fawoosh** [comment]
Here is another log. Just ran my leg 1 and it did not use fire extinguisher whatsoever. Ended the day with 100% charge left.
