### ISSUE TITLE
[BUG] Daylight savings bug? 

### ISSUE THREAD

**Issue by NoctiBeard** [loathers/garbage-collector#1720]
Also, read [this](BUGS.md).

**Describe the bug**
JavaScript exception: Error: Eep! It's a mere 82128 seconds until rollover!

**To Reproduce**

Run garbo

**Comment by ckrentz** [comment]
Having this issue as well. Updated Mafia, updated Garbo, tried restarting and clearing settings. Seems completely inoperable at the moment.

**Comment by horrible-little-slime** [comment]
Duplicate of #1721
