### ISSUE TITLE
[BUG] one of the gingerbread city NCs is broken

### ISSUE THREAD

**Issue by docrostov** [loathers/garbage-collector#1726]
**Describe the bug**
small issue with one of the gingerbread city NCs

![image](https://github.com/loathers/garbage-collector/assets/8014761/32822a84-4c24-42c9-a26d-d2189f350fe3)

this choice caused garbo to crash out unfortunately lol

**To Reproduce**
1. have gingerbread city
2. i don't know, my guess is this is w/ the new wanderer code?

**Expected behavior**
just handling of the choice

**Session Log**
[Captain_Scotch_20231110.txt](https://github.com/loathers/garbage-collector/files/13321239/Captain_Scotch_20231110.txt)

**Comment by docrostov** [comment]
on further examination what probably happened here is garbo meant to visit dressed in gingerbread best and did not do so? idk

**Comment by horrible-little-slime** [comment]
> > Executing Wanderers/Spit Acid
We didn't mean to be dressed in the gingerbread best; this'll be resolved by #1690
