### ISSUE TITLE
[BUG] Stuck in a loop when trying to adventure underwater

### ISSUE THREAD

**Issue by Kodazzle** [loathers/garbage-collector#1740]
[Oneshot_20231116.txt](https://github.com/loathers/garbage-collector/files/13384680/Oneshot_20231116.txt)

Hi There, 

This is my first bug report, so apologies if I get something wrong. I have read BUGS.md and will do my best to keep to the format. I have uploaded my session log as well. The bug occurs after garbo has done its initial buffing and setup. I think it gets fishy to go underwater, tries to adventure in "The Briny Deeps", gives a "You can't breathe underwater." error, then goes to Executing Wanders and just loops itself eternally. This is the loop:

> Preference nextAdventure changed from Barf Mountain to The Briny Deeps
> 
> Visit to The Sea: The Briny Deeps in progress...
> You can't breathe underwater.
> 
> Executing Wanderers/Digitize Wanderer
> Wandering at The Haunted Kitchen for expected value 0.00 (Default)
> 
> Visit to The Sea: The Briny Deeps in progress...
> You can't breathe underwater.
> 
> Executing Wanderers/Digitize Wanderer
> Wandering at The Haunted Kitchen for expected value 0.00 (Default)
> 
> Visit to The Sea: The Briny Deeps in progress...
> You can't breathe underwater.

repeat ad infinitum. 

That text isn't in the session log, but it does have similar loop just not in that text (starts on line 5600). 

**To Reproduce**

I'm not sure how to reproduce the bug, but without fail whenever i run garbo it happens (after initial diet, buffing etc). 

**Additional context**
This is my first major bug for garbo and I updated mafia and garbo, multiple times (i waited for a week in case this was a common bug and hoped an update would fix it), but i am still encountering the error. I bought the model train set IOTM recently, but i don't think that is causing this bug. 

It's worth noting that after interrupting garbo, then manually using a source of underwater breathing (i manually used a ballast turtle), and then re-running garbo still gives the same error, so it thinks i can't breathe underwater when i can? or it expects a wandering monster and it's not there? i don't really know how and why this bug is occurring, so i apologize if this is a vague bug report.  

Thank you for all the work you do on this project, i really appreciate it.

Kind Regards,
Kodazzle/Oneshot

**Comment by BlargZap** [comment]
to add further context - appears to be wanting to pulled green taffy an embezzler at the briny deeps, potentially obtaining fishy successfully (fishy pipe used), however breathing not handled correctly (including familiar). Manually handling and re-running garbo will successfully detect that a pulled green taffy has been used today, but won't use the envyfish egg.
