### ISSUE TITLE
[BUG] Garbo adventuring at Spacegate and getting stuck in a choice 

### ISSUE THREAD

**Issue by wetflame** [loathers/garbage-collector#1741]
**Describe the bug**
As part of garbo it is attempting to adventure in Spacegate (as part of the Wanderers?)

. As part of my pre-garbo scripting I adventure in specific Spacegate planets and I have set choices to use the geological sample kit in NCs like "Wide Open Spaces" (choice #1256). Garbo hits these NCs without the geological sample kit equipped and so cannot run the choice that I select, so gets stuck in the choice.

**To Reproduce**
Activate the Spacegate terminal for any planet with a "Wide Open Spaces" or "Cool Space Rocks" NC e.g. CHEVRON with the choice set to "acquire some more samples (with geological sample kit)." then run garbo?

**Expected behavior**
Either not adventure in Spacegate if it is already set, or perhaps set choices to something which does not require the equipment before adventuring there, and then reset the choice afterwards. 

**Session Log**
[King_Dave_20231117.txt](https://github.com/loathers/garbage-collector/files/13392828/King_Dave_20231117.txt)

**Additional context**
This is happening in post-CS aftercore

**Comment by horrible-little-slime** [comment]
I'll just cut spacegate from wanderers
