### ISSUE TITLE
[BUG] Won't nobarf with low valueOfAdventure

### ISSUE THREAD

**Issue by crowkol** [loathers/garbage-collector#1759]
**Before Reporting**
Everything is up to date as of this morning.  I'll admit, while this is bug like, it is kinda a feature request too.  I couldn't find a similar report.

**Describe the bug**
I have a character that doesn't have all the stuff needed to do barf farming better than volcano farming, but I'd still like to do "garbo nobarf" and have garbo farm KGE's etc, but garbo complains about my low valueOfAdventure.

**To Reproduce**
set valueOfAdventure = 3000
garbo nobarf
`JavaScript exception: Your valueOfAdventure is set to 3000, which is too low for barf farming to be worthwhile. If you forgot to set it, use "set valueOfAdventure = XXXX" to set it to your marginal turn meat value.`

**Expected behavior**
I like it to do the stuff garbo does before barf farming and then quit.  The error message doesn't make sense given I told it not to barf farm.

I totally realize this is an edge case and I'd look into it myself, but I can't read javascript.

**Comment by Malibu-Stacey** [comment]
If you're volcano farming, your VoA isn't 3k and this is easily worked around by just setting the value at the threshold.
Rejecting this as it's contrary to the whole reason for this script existing.
