### ISSUE TITLE
[BUG] Garbo/combat macro aborting on Embezzler encounters

### ISSUE THREAD

**Issue by DEEX3545** [loathers/garbage-collector#1787]
Mafia version: 27775
Garbo version: updated to main as of 1/5/24

**Describe the bug**
Precontext: 
I was encountering the issue where garbo was failing to recover from beaten up gained from June Cleaver so I decided to reinstall everything  @(#1715). This involved deleting all directories in my root mafia directory and rerunning and reinstalling my scripts. Zlib was acquired from the script manager in mafia and garbo and universal recovery were installed by the methods outlined on the garbo readme.

Bug context: with the reinstall finished, in addition to failing from recovering from June Cleaver's beaten up, garbo was also aborting combat against digitized Embezzlers. Manually opening KoL in browser and executing the generated combat macro that garbo creates works and then I can rerun garbo. However, it will abort once encountering another embezzler.

**To Reproduce**
Occurs whenever an embezzler is encountered.
Manually finishing combat and rerunning will allow garbo to continue until another embezzler is encountered.

**Session Log, other pictures and info**
[warballs_20240105.txt](https://github.com/loathers/garbage-collector/files/13845923/warballs_20240105.txt)

![js_error](https://github.com/loathers/garbage-collector/assets/31356869/a5ac6edd-bfc3-4229-bf69-611d13b36557)

![embezzler](https://github.com/loathers/garbage-collector/assets/31356869/7d5848d3-f5c1-4ab6-bb9f-be34133b7520)

Macro text:

`if hasskill Sing Along;skill Sing Along;endif;if monsterid 1760;if hasskill Transcendent Olfaction;skill Transcendent Olfaction;endif;endif;if monsterid 1760;if hasskill Offer Latte to Opponent;skill Offer Latte to Opponent;endif;endif;if monstername angry tourist || monstername garbage tourist || monstername horrible tourist family || monstername Knob Goblin Embezzler || monstername sausage goblin;if !hppercentbelow 25;if hasskill 7273;skill 7273;endif;endif;while !hppercentbelow 25 && !pastround 20;use seal tooth;endwhile;endif;if hasskill Furious Wallop;skill Furious Wallop;endif;while !pastround 24 && !hppercentbelow 25 && !missed 1 && !snarfblat 567;attack;endwhile;while hasskill Saucegeyser;skill Saucegeyser;endwhile;while hasskill Weapon of the Pastalord;skill Weapon of the Pastalord;endwhile;while hasskill Cannelloni Cannon;skill Cannelloni Cannon;endwhile;while hasskill Wave of Sauce;skill Wave of Sauce;endwhile;while hasskill Saucestorm;skill Saucestorm;endwhile;while hasskill Northern Explosion && snarfblat 567;skill Northern Explosion;endwhile;while hasskill Lunging Thrust-Smack && !snarfblat 567;skill 1005;endwhile;attack;repeat;`

**Additional context**
Been in post ronin for quite a bit. I have a source terminl and the error seems to be confusing normal embezzlers and digitized ones? (no idea if that's the problem)

**Comment by horrible-little-slime** [comment]
Do you have autoattack against special monsters enabled? It looks like our autoattack isn't triggering properly, making our fallthrough macro trigger, which is designed to only work if the autoattack macro isn't triggering.

Garbo _should_ be automatically checking that box itself, but it could be failing to.

**Comment by DEEX3545** [comment]
It was the autoattack against special monster setting. Checking the box has fixed my issue but from rerunning Garbo multiple times it seems like it was failing to check it. Thank you!
