### ISSUE TITLE
Free Fight/Kramco Using Advs and Wandering in Shadow Rift (Desert Beach)

### ISSUE THREAD

**Issue by Tapionator** [loathers/garbage-collector#1789]
Currently I am a Seal Clubber running garbo nodiet nobarf workshed="cmc" and am running into this problem. Honestly it's been occuring for a month now. When doing my free fights, garbo will have my character adventure at the shadow rift (Desert Beach) to use a yellow ray but, instead of using the yellow ray it is consuming adventures. In addition, it says it is attempting to fight a sausage goblin (which is odd since the shadow rifts are no wander). It usually eats up about 5-6 advs. Appreciate it! Please see below for log details (I bolded what I felt was most relavent to the bug). 

**> Executing Free Fight/Kramco**

familiar Cookbookbat (100 lbs)
Preference _concoctionDatabaseRefreshes changed from 603 to 604

equip familiar amulet coin
Preference _concoctionDatabaseRefreshes changed from 604 to 605
Maximizer: Familiar Weight, -"equip Amulet of Perpetual Darkness", -"equip Buddy Bjorn", -"equip Spooky Putty ball", -"equip Spooky Putty leotard", -"equip Spooky Putty mitre", -"equip Spooky Putty snake", -"equip broken champagne bottle", -"equip dice-shaped backpack", -"equip papier-masque", -"equip papier-mitre", -"equip smoke ball", -"equip stinky fannypack", -"equip ¶5868", -"equip ¶5869", -"equip ¶5872", -buddy-bjorn, -crown-of-thrones, -off-hand, 1028.54 "bonus lucky gold ring", 1100.49 "bonus Pantsgiving", 145.95 "bonus rake", 145.95 "bonus tiny rake", 180 "bonus Mr. Screege's spectacles", 180 "bonus Snow Suit", 185.75 "bonus Crown of Thrones", 220 "bonus Mr. Cheeng's spectacles", 273.36 "bonus June cleaver", 333.58 "bonus can of mixed everything", 500 "bonus tiny stillsuit", 6.25 "bonus Powerful Glove"

Unequip Baby Sandworm
Preference _concoctionDatabaseRefreshes changed from 605 to 606

equip familiar tiny stillsuit
Preference _concoctionDatabaseRefreshes changed from 606 to 607
Preference _concoctionDatabaseRefreshes changed from 607 to 608
> Maximize: Familiar Weight
> CCS: [default]\n "if hasskill Sing Along;skill Sing Along;endif;if hasskill Curse of Weaksauce;skill Curse of Weaksauce;endif;if hasskill Pocket Crumbs;skill Pocket Crumbs;endif;if hasskill 7273;skill 7273;endif;if hasskill Micrometeorite;skill Micrometeorite;endif;if hascombatitem Time-Spinner;use Time-Spinner;endif;while !pastround 3 && !hppercentbelow 25;use seal tooth;endwhile;while !pastround 24 && !hppercentbelow 25 && !missed 1 && !snarfblat 567;attack;endwhile;while hasskill Saucegeyser;skill Saucegeyser;endwhile;while hasskill Weapon of the Pastalord;skill Weapon of the Pastalord;endwhile;while hasskill Cannelloni Cannon;skill Cannelloni Cannon;endwhile;while hasskill Wave of Sauce;skill Wave of Sauce;endwhile;while hasskill Saucestorm;skill Saucestorm;endwhile;while hasskill Northern Explosion && snarfblat 567;skill Northern Explosion;endwhile;while hasskill Lunging Thrust-Smack && !snarfblat 567;skill 1005;endwhile;attack;repeat;"
> Autoattack macro: if hasskill Sing Along;skill Sing Along;endif;if hasskill Curse of Weaksauce;skill Curse of Weaksauce;endif;if hasskill Pocket Crumbs;skill Pocket Crumbs;endif;if hasskill 7273;skill 7273;endif;if hasskill Micrometeorite;skill Micrometeorite;endif;if hascombatitem Time-Spinner;use Time-Spinner;endif;while !pastround 3 && !hppercentbelow 25;use seal tooth;endwhile;while !pastround 24 && !hppercentbelow 25 && !missed 1 && !snarfblat 567;attack;endwhile;while hasskill Saucegeyser;skill Saucegeyser;endwhile;while hasskill Weapon of the Pastalord;skill Weapon of the Pastalord;endwhile;while hasskill Cannelloni Cannon;skill Cannelloni Cannon;endwhile;while hasskill Wave of Sauce;skill Wave of Sauce;endwhile;while hasskill Saucestorm;skill Saucestorm;endwhile;while hasskill Northern Explosion && snarfblat 567;skill Northern Explosion;endwhile;while hasskill Lunging Thrust-Smack && !snarfblat 567;skill 1005;endwhile;attack;repeat;
**> Wandering at Shadow Rift (Desert Beach) for expected value 17290.54 (Yellow Ray Shadow Rift (Desert Beach))**

**[702] Shadow Rift (Desert Beach)**
Preference lastEncounter changed from shadow devil to shadow snake
Encounter: shadow snake
Preference _shadowRiftCombats changed from 9 to 10
Round 0: Tapion wins initiative!
Preference cosmicBowlingBallReturnCombats changed from 13 to 12
Round 0: Tapion casts SING ALONG!
Round 1: Tapion casts CURSE OF WEAKSAUCE!
Round 2: shadow snake drops 7 attack power.
Round 2: shadow snake drops 6 defense.
Round 2: Tapion casts POCKET CRUMBS!
Round 3: shadow snake drops 19 attack power.
Round 3: shadow snake drops 16 defense.
Round 3: shadow snake drops 6 attack power.
Round 3: shadow snake drops 7 defense.
Round 3: Tapion casts EXTRACT!
You acquire an item: Source essence
Round 4: shadow snake drops 6 attack power.
Round 4: shadow snake drops 6 defense.
Round 4: Tapion casts MICROMETEORITE!
Round 5: shadow snake drops 13 attack power.
Round 5: shadow snake drops 14 defense.
Round 5: shadow snake drops 7 attack power.
Round 5: shadow snake drops 7 defense.
Preference _micrometeoriteUses changed from 57 to 58
Round 5: Tapion uses the Time-Spinner!
Round 6: shadow snake drops 5 attack power.
Round 6: shadow snake drops 5 defense.
Round 6: shadow snake drops 6 attack power.
Round 6: shadow snake drops 6 defense.
Round 6: Tapion casts SAUCEGEYSER!
Round 7: shadow snake takes 469 damage.
Round 7: shadow snake drops 8 attack power.
Round 7: shadow snake drops 8 defense.
Round 7: Tapion wins the fight!
After Battle: A love cricket plays a jaunty tune for you. You tap your feet.
Preference lovebugsItemDrop changed from 48 to 49
After Battle: Graraham surveys the scene from atop the throne, and gains 1 Experience.
You gain 268 Meat
After Battle: These things are heavier than they look!
After Battle: You gain 5 Muscleboundness
After Battle: Bat...Man no wait! BatBat, perfect flits around and points at cooking ingredients.
You acquire an item: shadow sinew
After Battle: You think you see a weird thing out of the corner of your eye, but it turns out to be nothing. Which is actually pretty weird, if you think about it, man.
After Battle: You notice some extra Meat hidden beneath an emptiness.
You gain 20 Meat.
After Battle: You gain 50 Beefiness
After Battle: You gain 53 Wizardliness
After Battle: You gain 44 Cheek
After Battle: You remember, from the map in your mind, an area underneath the void with a cache of meat!
You gain 78 Meat.
You acquire an item: inflammable leaf (2)
After Battle: Bat...Man no wait! BatBat, perfect looks off in the distance before speaking, "As I recall, St. Sneaky Pete's Whey was common in The Haunted Conservatory, back in my day. Perhaps if you kill a man-eating plant, you'll find one."
After Battle: You gain 2 Magicalness
Preference _juneCleaverFightsLeft changed from 8 to 7
Preference _juneCleaverStench changed from 15 to 16
Preference _pantsgivingCount changed from 48 to 49
Preference encountersUntilSRChoice changed from 7 to 6
Preference lastCopyableMonster changed from shadow devil to shadow snake
Preference _boomBoxFights changed from 0 to 1
Preference familiarSweat changed from 235 to 238
Preference autumnatonQuestTurn changed from 339718 to 339717
Preference _concoctionDatabaseRefreshes changed from 608 to 609
**> Task Free Fight/Kramco spent a turn but was marked as not spending turns**
Preference _concoctionDatabaseRefreshes changed from 609 to 610

**Comment by Tapionator** [comment]
Adding this as I discovered this within the code. Unsure if it's related to the problem or not. It seems odd that the Yellow Ray is identified as a string in this situaion. I feel like the Kramco/Free fight function is identifying it's location off of the "Yellow Ray" location rather than the "wanderer" location thus causing the weird issue. 

 function wandererTurnsAvailableToday(options, location) {
      var canWanderCache = {
        backup: canWander(location, "backup"),
        wanderer: canWander(location, "wanderer"),
        **"yellow ray"**: canWander(location, "yellow ray"),
        freefight: canWander(location, "freefight")
      };

**Comment by horrible-little-slime** [comment]
Can you attach a complete log? I'd like to look for other irregularities.

**Comment by Tapionator** [comment]
Thank you for looking into this! File as requested from earlier today. 
[Tapion_20240111.txt](https://github.com/loathers/garbage-collector/files/13909391/Tapion_20240111.txt)
