### ISSUE TITLE
[BUG] JavaScript exception: KoLmafia error: Fluffy bunny is supposedly banished by Feel Hatred, but this appears not to be the case.

### ISSUE THREAD

**Issue by shavbi** [loathers/garbage-collector#1803]
**Describe the bug**
Encountered the following error while running garbo after ronin cleared hardcore community service.
JavaScript exception: KoLmafia error: Fluffy bunny is supposedly banished by Feel Hatred, but this appears not to be the case; the most likely issue is that your _monsterHabitatsMonster preference is nonzero and should probably be zero.

before this error, yesterday it was:
Fluffy bunny is supposedly banished by ice house
where i had fluffy bunny in the ice house. i proceeded to melt it, and the next error is:
Fluffy bunny is supposedly banished by louder than bomb.
i proceeded to manually make a louder than bomb, and used it against fluffy bunny, this was done using relay browser while running kolmafia.
today's error is as above.

i have a script to refresh session and re-run garbo. everytime i encounter this error, i will run that script, and it will error out 3 times before proceeding to complete the garbo script and run the rest of my scripts.

**Expected behavior**
I would not expect the script to abort.

**Session Log**
[CryptoBro_20240125.txt](https://github.com/loathers/garbage-collector/files/14047703/CryptoBro_20240125.txt)
JavaScript exception: KoLmafia error: Fluffy bunny is supposedly banished by Feel Hatred, but this appears not to be the case; the most likely issue is that your _monsterHabitatsMonster preference is nonzero and should probably be zero.
at file:/C:/Users/shavb/Dropbox/Games/KoL/Mafia/scripts/garbage-collector/garbo.js:38010 (runGregFight)
at file:/C:/Users/shavb/Dropbox/Games/KoL/Mafia/scripts/garbage-collector/garbo.js:38021
at file:/C:/Users/shavb/Dropbox/Games/KoL/Mafia/scripts/garbage-collector/garbo.js:37802 (run)
at file:/C:/Users/shavb/Dropbox/Games/KoL/Mafia/scripts/garbage-collector/garbo.js:40876 (runEmbezzlerFight)
at file:/C:/Users/shavb/Dropbox/Games/KoL/Mafia/scripts/garbage-collector/garbo.js:42725
at file:/C:/Users/shavb/Dropbox/Games/KoL/Mafia/scripts/garbage-collector/garbo.js:39901 (withStash)
at file:/C:/Users/shavb/Dropbox/Games/KoL/Mafia/scripts/garbage-collector/garbo.js:42619 (dailyFights)
at file:/C:/Users/shavb/Dropbox/Games/KoL/Mafia/scripts/garbage-collector/garbo.js:48205
at file:/C:/Users/shavb/Dropbox/Games/KoL/Mafia/scripts/garbage-collector/garbo.js:39922 (withClan)
at file:/C:/Users/shavb/Dropbox/Games/KoL/Mafia/scripts/garbage-collector/garbo.js:39916 (withVIPClan)
at file:/C:/Users/shavb/Dropbox/Games/KoL/Mafia/scripts/garbage-collector/garbo.js:48183
at file:/C:/Users/shavb/Dropbox/Games/KoL/Mafia/scripts/garbage-collector/garbo.js:39901 (withStash)
at file:/C:/Users/shavb/Dropbox/Games/KoL/Mafia/scripts/garbage-collector/garbo.js:48182 (main)

prefref _monsterHabitatsMonster yields:    
Name | Value | Default | Scope
_monsterHabitatsMonster | 0 |   | user

prefref banishedMonsters yields:
fluffy bunny:Feel Hatred:113:Ancient Mariner:snokebomb:155:toothless mastiff bitch:Reflex Hammer:155:crate:Throw Latte on Opponent:155:fluffy bunny:louder than bomb:160

**Additional context**
This happens post-loop only, never pre-loop. To elaborate, I ran garbo on my post-CS day 2, then run CS, then run garbo after that, and this happens. It has been around for at least 3months now.

**Comment by horrible-little-slime** [comment]
> Preference _saberForceMonsterCount changed from 3 to 2

Seems like your script is using the force to ensure that only bunnies can be obtained in the dire warren

**Comment by shavbi** [comment]
thank you very much for the guidance, yes i think i saber fluffy bunny for the fire extinguisher thingie in my CS run.
