### ISSUE TITLE
[BUG] LoL path getting stuck on the sea

### ISSUE THREAD

**Issue by m4z4r** [loathers/garbage-collector#1808]
**Describe the bug**

Garbo is getting stuck on 

Executing Daily Sea/Unlock The Sea
CCS set to grimoire_macro
Autoattack is disabled.

**To Reproduce**

Run garbo in LoL path 

**Session Log**

> garbo

Using adventure value 4400.
You need 1 more Claw of the Infernal Seal to continue.
Local Version: 8670f87e5ea45de898861e562d473a2b40601aff (built from main@85c23872c0766e8ae75a7eb4b2be8ba7679aff15)
Garbo is up to date!
I have set auto-confirm to true and accept all ramifications that come with that.
Automatically selected true for Looks like your ascension may not be done, or you may be severely underleveled. Running garbo in an unintended character state can result in serious injury and even death. Are you sure you want to garbologize?
Collecting garbage!

Autoattack is disabled.
Preference battleAction changed from attack with weapon to custom combat script
Preference customCombatScript changed from custom to garbo
CCS set to garbo
autoSatisfyWithStash => false
Preference autoSatisfyWithStash changed from true to false
hpAutoRecoveryTarget => 0
Preference hpAutoRecoveryTarget changed from 1.0 to 0
mpAutoRecoveryTarget => 0
Preference mpAutoRecoveryTarget changed from 0.5 to 0
allowSummonBurning => true
Preference allowSummonBurning changed from false to true
libramSkillsSoftcore => none
Preference libramSkillsSoftcore changed from all to none

Talking to the Old Man
Refreshing stash contents...
Stash list retrieved.
Refreshing stash contents...
Stash list retrieved.
Refreshing stash contents...
Stash list retrieved.
Refreshing stash contents...
Stash list retrieved.
Refreshing stash contents...
Stash list retrieved.
Refreshing stash contents...
Stash list retrieved.
Refreshing stash contents...
Stash list retrieved.
Skipping fancy chocolate sculpture; too expensive (73696 > 27000).
Searching for "possessed sugar cube"...
Search complete.
allowNonMoodBurning => false
Preference allowNonMoodBurning changed from true to false
Preference customCombatScript changed from garbo to grimoire_macro
CCS set to grimoire_macro

Executing Daily Familiars/Moveable feast
CCS set to grimoire_macro
Autoattack is disabled.
Refreshing stash contents...
Stash list retrieved.

Executing Daily/Configure I Voted! Sticker
Autoattack is disabled.

Executing Daily/Verify Horsery
Autoattack is disabled.

Executing Daily/defective Game Grid token
Autoattack is disabled.
Refreshing stash contents...
Stash list retrieved.
Searching for "defective Game Grid token"...
Search complete.
Desired purchase quantity not reached (wanted 1, got 0)
Searching for "defective Game Grid token"...
Search complete.
Desired purchase quantity not reached (wanted 1, got 0)
You need 1 more defective Game Grid token to continue.

Executing Daily/Use BittyCar MeatCart
Autoattack is disabled.
Refreshing stash contents...
Stash list retrieved.
Searching for "BittyCar MeatCar"...
Search complete.
Desired purchase quantity not reached (wanted 1, got 0)
Searching for "BittyCar MeatCar"...
Search complete.
Desired purchase quantity not reached (wanted 1, got 0)
You need 1 more BittyCar MeatCar to continue.

Executing Daily/Use BittyCar SoulCar
Autoattack is disabled.
Refreshing stash contents...
Stash list retrieved.
Searching for "BittyCar SoulCar"...
Search complete.
Desired purchase quantity not reached (wanted 1, got 0)
Searching for "BittyCar SoulCar"...
Search complete.
Desired purchase quantity not reached (wanted 1, got 0)
You need 1 more BittyCar SoulCar to continue.

Executing Daily/Check Barf Mountain Quest
Autoattack is disabled.

Visiting the Employee Assignment Kiosk

Executing Daily Items/Treat
CCS set to grimoire_macro

Executing Daily Sea/Unlock The Sea
CCS set to grimoire_macro
Autoattack is disabled.

Talking to the Old Man
hpAutoRecoveryTarget => 0
Preference hpAutoRecoveryTarget changed from 0.0 to 0
mpAutoRecoveryTarget => 0
Preference mpAutoRecoveryTarget changed from 0.0 to 0
allowNonMoodBurning => true
Preference allowNonMoodBurning changed from false to true
Preference customCombatScript changed from grimoire_macro to garbo
CCS set to garbo
Autoattack is disabled.
Preference choiceAdventure1387 changed from -1 to 2
Refreshing stash contents...
Stash list retrieved.
Preference battleAction changed from custom combat script to attack with weapon
Preference customCombatScript changed from garbo to custom
CCS set to custom
(but battle action is currently set to attack with weapon)
autoSatisfyWithStash => true
Preference autoSatisfyWithStash changed from false to true
hpAutoRecoveryTarget => 1
Preference hpAutoRecoveryTarget changed from 0.0 to 1
mpAutoRecoveryTarget => 0.5
Preference mpAutoRecoveryTarget changed from 0.0 to 0.5
allowSummonBurning => false
Preference allowSummonBurning changed from true to false
libramSkillsSoftcore => all
Preference libramSkillsSoftcore changed from none to all
valueOfInventory => 2
Preference valueOfInventory changed from 2.0 to 2
Preference choiceAdventure1387 changed from 2 to -1
You fought 0 Knob Goblin Embezzler at the beginning of the day, and an additional 0 digitized Knob Goblin Embezzler throughout the day. Good work, probably!
Including this, you have fought 0 across all ascensions today
Extreme Items:
This run of garbo, across 0 turns you generated 0 meat, with 0 raw meat and 0 from items
So far today, across 0 turns you generated -437,094 meat, with -175,583 raw meat and -261,511 from items
JavaScript exception: Error: Failed to build outfit from {"famequip":["little bitty bathysphere","das boot"],"modifier":["ML 100 Max","-Familiar Weight"],"avoid":["Drunkula's wineglass"],"familiar":"Patriotic Eagle"} (file:/C:/Users/bradb/Desktop/KolMafia/scripts/garbage-collector/garbo.js#42315)
at file:/C:/Users/bradb/Desktop/KolMafia/scripts/garbage-collector/garbo.js:42315 (f)
at file:/C:/Users/bradb/Desktop/KolMafia/scripts/garbage-collector/garbo.js:43598
at file:/C:/Users/bradb/Desktop/KolMafia/scripts/garbage-collector/garbo.js:39901 (withStash)
at file:/C:/Users/bradb/Desktop/KolMafia/scripts/garbage-collector/garbo.js:43588 (freeRunFights)
at file:/C:/Users/bradb/Desktop/KolMafia/scripts/garbage-collector/garbo.js:43626 (freeFights)
at file:/C:/Users/bradb/Desktop/KolMafia/scripts/garbage-collector/garbo.js:48202
at file:/C:/Users/bradb/Desktop/KolMafia/scripts/garbage-collector/garbo.js:39922 (withClan)
at file:/C:/Users/bradb/Desktop/KolMafia/scripts/garbage-collector/garbo.js:39916 (withVIPClan)
at file:/C:/Users/bradb/Desktop/KolMafia/scripts/garbage-collector/garbo.js:48183
at file:/C:/Users/bradb/Desktop/KolMafia/scripts/garbage-collector/garbo.js:39901 (withStash)
at file:/C:/Users/bradb/Desktop/KolMafia/scripts/garbage-collector/garbo.js:48182 (main)

**Comment by s-k-z** [comment]
Unfortunately, running it during an ascension is not supported.
> I have set auto-confirm to true and accept all ramifications that come with that.
Automatically selected true for Looks like your ascension may not be done, or you may be severely underleveled. Running garbo in an unintended character state can result in serious injury and even death. Are you sure you want to garbologize?

**Comment by m4z4r** [comment]
When did this happen? I used to run Garbo in LoL path after out of ronin
months ago and it was fine

**Comment by s-k-z** [comment]
#392 was added in 2021 to state that in-run usage is not intended to be supported.

The most straightforward solutions:
1) complete all the council quests and free the king, or
2) address the error `Failed to build outfit from {"famequip":["little bitty bathysphere","das boot"...` by acquiring a das boot for permanent use, or
3) manually acquire the effect `Citizen of Barf Mountain` by using the Patriotic Eagle in combat at Barf Mountain.

The specific issue you are encountering is that neither of those two items are available for minimizing familiar weight for the Patriotic Eagle. It is possible that you didn't run into this in Legacy of Loathing before due to not owning this familiar, or because you ran it before support for it was added.

**Comment by m4z4r** [comment]
Thanks for that detailed answer, and thank you for your work on this
wonderful script!
