### ISSUE TITLE
[BUG] Garbo Can't Build A Meatcar

### ISSUE THREAD

**Issue by tsuyoshikentsu** [loathers/garbage-collector#1828]
**Describe the bug**
If garbo attempts to use a drum machine without having unlocked the Beach, it will get stuck in an infinite loop of attempting to use the machine over and over.

**To Reproduce**

1. Break prism without having unlocked the Beach--Community Service is probably the easiest (and might be the only) way to do this.
2. Run garbo.

**Expected behavior**
Given garbo's ability to buy and craft items, I would assume it could execute "make bitch" in the CLI.

**Session Log**
The only red text was "Can't find the beach"
[ahdar_musicstopper_20240324.txt](https://github.com/loathers/garbage-collector/files/14734306/ahdar_musicstopper_20240324.txt)

**Additional context**
This seems to happen any time the beach is not unlocked across several ascensions. I usually just do it myself--it's not hard for _me_ to enter "make bitch" in the CLI either--but I forget sometimes and it's very annoying.

**Comment by horrible-little-slime** [comment]
https://kolmafia.us/threads/lastdesertunlock-improperly-set.26371/
