### ISSUE TITLE
[BUG] Stuck in loop after closeting closed-circuit pay phone

### ISSUE THREAD

**Issue by MrFizzyBubbs** [loathers/garbage-collector#1838]
**Before Reporting**
Ensure that KoLMafia and garbo are both up to date before reporting a bug. If you have installed mafia in a weird or non-standard way, let us know any details about that here. But also, if you've installed mafia in a weird or non-standard way, I'm telling you right now that that's your bug. Also, check existing github issues to see if this has already been reported. If it has, consider leaving a comment with any additional information you can give on _that_ issue, instead of making a new one.

Also, read [this](BUGS.md).

**Describe the bug**
After closeting the closed-circuit pay phone today since it is salad day, garbo gets stuck in a loop trying to adventure in a shadow right which it can no longer access.

**To Reproduce**

1. Put your closed-circuit pay phone in your closet
2. Run garbo

**Expected behavior**
Garbo skips the shadow rifts if they are not available.

**Session Log**
[shadow_rift_log.txt](https://github.com/loathers/garbage-collector/files/14824657/shadow_rift_log.txt)

**Additional context**
My preferences at the time of running. I previously ran garbo with the pay phone not closeted and had to manually intervene before closeting it.
![image](https://github.com/loathers/garbage-collector/assets/82386733/ff58dddf-a696-436c-a3a7-00d53588b415)

**Comment by horrible-little-slime** [comment]
`prefref autoSatisfy`?

**Comment by MrFizzyBubbs** [comment]
![image](https://github.com/loathers/garbage-collector/assets/82386733/0cbddb55-9be2-4504-bb9b-77481a20dc78)

**Comment by horrible-little-slime** [comment]
turn off `autoSatisfyWithCloset` if you want scripts to truly ignore your closeted items. While we do have a `.have()` check, ultimately the fact that we check `canAdventure` means that this is partially a mafia issue. But mostly the autosatisfywithcloset thing.
