### ISSUE TITLE
Extra Time Use/Meat Calculation Error [BUG]

### ISSUE THREAD

**Issue by Tapionator** [loathers/garbage-collector#1843]
I've noticed my runs never using Extra Time despite my mpa exceeding the value of +5 advs that would be gained upon use of the Extra Time purchased from the mall. 

I was able to manually correct this when setting the extraTimeUsed pref to 1 instead of the default 0. 

When preference  extraTimeUsed=0, garbo will not think Extra Time is usable resulting in non-use.

When preference  extraTimeUsed=1, garbo will calculate the use of Extra Time as 5 advs gained rather than 3 advs and utilize the Extra Time. 

Example (from session log): 
MPA set to 8000, (after using an extra time for testing purposes for the +5 advs and rerunning Garbo)

> Trying to acquire 1 extra times; max price 40000.

use 1 extra time
You gain 3 Adventures
Preference _extraTimeUsed changed from 1 to 2
Preference _concoctionDatabaseRefreshes changed from 1781 to 1782

**Comment by pstalcup** [comment]
Should be addressed by https://github.com/loathers/garbage-collector/pull/1844

**Comment by Tapionator** [comment]
Awesome thank you :D
