### ISSUE TITLE
[FEATURE] - Spring Shoes, Apriling Usage

### ISSUE THREAD

**Issue by Tapionator** [loathers/garbage-collector#1854]
Unsure if these are already in the works but figured I'd throw it out there. There may be better ways to approach these..

**Spring Shoes Usage:** Utilize Spring shoes for additional free runaways to build up towards Shadows Water Buff and/or Gingerbread NC (may be better location but this makes most sense imo).

Logic: 
If next fight is not KGE, and "Everything looks Green" is not active as an effect, and Gingerbread City is available and availableMidnights =true, adventure at Gingerbread City and utilize spring shoes as free run source, or if Gingerbread city is not available, and currently do not have the effect "Everything Looks Green," adventure at Shadow Rift (if available) and utilize macro that includes using Spring shoes for free runaway. 

**Apriling Usage:** Use Apriling hat for 3 more KGEs and Quad Tom for 3 free sandworm fights

Logic:
If has Apriling hat, summon Saxophone and Quad Tom,

During KGE fights, if Cobb Knob Treasury is available, and Saxophone uses are not equal to 3, utilize Saxophone, maximize meat, adventure at Treasury.

During Sandworm fights, if Quad Tom Tom uses are not equal to 3, maximize item, use Tom Tom

**Comment by wetflame** [comment]
Garbo is trying to use Spring Shoes but I don't have them unboxed, so I'm getting this error:

`JavaScript exception: Combat exception! Last macro error: Too many, or zero, matches for skill, "Spring Away", macro aborted.. Exception KoLmafia error: You're on your own, partner. (Too many, or zero, matches for skill, "Spring Away", macro aborted.). (file:/.../scripts/garbage-collector/garbo.js#40748)`
