### ISSUE TITLE
[BUG] Apriling piccolo bug

### ISSUE THREAD

**Issue by Arashmin** [loathers/garbage-collector#1856]
If the script picks apriling piccolo, the script was silently freezing when it tries to use it for Pocket Professor.  It appears the issue is that the piccolo becomes unusable by a familiar past a certain weight/experience threshold.  My Pocket Professor was 19 pounds, and when trying to use it manually I got a message that 'Your familiar doesn't feel like playing the piccolo right now'.

Using the piccolo up on my dramadery fixed it enough to allow the script to proceed.

Recommended fix: If the piccolo is picked, the script should watch for the fail-to-use message, and if it comes up, use the piccolo for another familiar.

**Comment by Arashmin** [comment]
Session file: 
[Arashmin_20240423.txt](https://github.com/loathers/garbage-collector/files/15078310/Arashmin_20240423.txt)

**Comment by weirandrewr** [comment]
set _aprilBandPiccoloUses = 3 if you're having issues
