### ISSUE TITLE
[BUG] Drum machine / Apriling quad tom failing to find the beach after Community Service runs

### ISSUE THREAD

**Issue by Arashmin** [loathers/garbage-collector#1857]
For CS looping, the beach never ends up being unlocked.  I've noticed multiple instances where this will cause the script to get stuck in an endless loop, where it tries to use a drum machine but then can't find the beach.

Recommended fix: Unlock the beach with the bus pass if it ever comes up as locked, or add a pref on whether or not to do so.

**Comment by Arashmin** [comment]
I don't always go farming after CS, though.  Sometimes I'll run other content.

**Comment by horrible-little-slime** [comment]
https://kolmafia.us/threads/lastdesertunlock-improperly-set.26371/
