### ISSUE TITLE
[BUG] - Numberology Only Cast Once per run

### ISSUE THREAD

**Issue by Tapionator** [loathers/garbage-collector#1897]
Error, only using numberology once per run instead of the 5 times I can, I believe I found the issue here with the completed function, the  **return get("_universeCalculated") >= get("skillLevel144");** should probably be this instead (note this was from an older version of garbo where this issue did not exist): 

  **if ((0, import_kolmafia88.myAdventures)() > 0 && Object.keys((0, import_kolmafia88.reverseNumberology)()).includes("69") && get("_universeCalculated") < get("skillLevel144"))**

Syntax Error Location:

function numberology() {
  return {
    name: "Numberology",
    ready: function() {
      return Object.keys((0, import_kolmafia121.reverseNumberology)()).includes("69");
    },
    completed: function() {
      **return get("_universeCalculated") >= get("skillLevel144");**
    },
    do: function() {
      return (0, import_kolmafia121.cliExecute)("numberology 69");
    },
    available: function() {
      return get("_universeCalculated") < get("skillLevel144");
    }
  };

**Comment by gausie** [comment]
The code looks correct. What is your value of skillLevel144?

**Comment by Tapionator** [comment]
It is 1, ah this is an error on my end (prefs got messed up a couple weeks ago). Thanks Gausie I'll close this.
