### ISSUE TITLE
Mayflower Bouquet Not Pulled or Returned to Clan Stash [BUG]

### ISSUE THREAD

**Issue by Tapionator** [loathers/garbage-collector#1899]
Mayflower Bouquet in clan stash is not pulled or returned to stash. Thought maybe this was due to it being not optimal but, when I have one in my inventory it does equip it during the run (during free fights). Thanks!

**Comment by horrible-little-slime** [comment]
That's not what "bug" means!

**Comment by Tapionator** [comment]
Wasn't sure if it not being pulled to begin with was a bug since when I have one garbo is always using it since I remember it being pulled on older versions. If I am recollecting incorrectly then I apologize it should of been a feature request :P

**Comment by Tapionator** [comment]
Thank you for the quick response and sorry for the delayed one
