### ISSUE TITLE
[BUG] Not all buffs are obtained before using PYEC before free fights

### ISSUE THREAD

**Issue by C2Talon** [loathers/garbage-collector#1934]
**Describe the bug**
https://github.com/loathers/garbage-collector/commit/84179a3f749485f36702bcbc3382456c7d06257b was the change that made it so buffing is done, and PYEC is used, before free fights. The problem is that it completely misses several buffs that are obtained as part of the free fights process. Immediately after using PYEC it uses blue taffy to get that buff, and then during free fights it also gets the wolf form (which is a combat skill, so it can't be done before fights), squint, KGB, and other buffs. Also, it doesn't even try to maximize MP before using the PYEC that early, but for some reason garbo will still maximize for MP at the end of free fights where it used to use PYEC, but then do nothing with the MP it maximized for.

**Expected behavior**
Get all of the buffs before using PYEC. Also, maximize MP before PYEC.

**Comment by horrible-little-slime** [comment]
Reverted the PR; we do expect to re-implement the feature but better later on. Thanks!
