### ISSUE TITLE
[BUG] Combat state gets "forgotten" and client ends up trying to mall and being redirected to fight

### ISSUE THREAD

**Issue by AngeloLansbury** [loathers/garbage-collector#1958]
**Describe the bug**
When I run garbo, after eating/drinking/et al, it gets into a fight with an embezzler, appears to forget it did so, and gets hung up trying to go to the mall.  It also asks me to clover for an embezzler multiple times.  The final error is complaining that mall redirects to a fight page.

**To Reproduce**
> garbo

**Expected behavior**
Adventure for fun an profit.

**Session Log**
[jtoomey_20240702.txt](https://github.com/user-attachments/files/16069418/jtoomey_20240702.txt)

**Comment by horrible-little-slime** [comment]
https://kolmafia.us/threads/enabling-show-old-form-with-combat-action-bar-breaks-end-of-fight-tracking.29484/
tangentially related: https://github.com/loathers/garbage-collector/issues/1824
