### ISSUE TITLE
Latte Lover's Members Mug Combat Skills Not Used?

### ISSUE THREAD

**Issue by Ancarlson7** [loathers/garbage-collector#1961]
My mug never uses its gulp for MP replenishing or its banishes. Feels like that could increase farming at barf for 90 adventures at a minimum and save cost for other mana regeneration. Maybe I'm missing something though, not an expert and just started using garbo.

**Comment by Rinn** [comment]
mana regen isn't really an issue (especially if you have a porquoise-handled sixgun) and you can't banish monsters in barf
