### ISSUE TITLE
KGE fight Aborts: KoLmafia thinks it is round 2 but KoL thinks it is round 1 You're on your own, partner. (Macro Aborted ("abort")) [BUG]

### ISSUE THREAD

**Issue by Tapionator** [loathers/garbage-collector#1963]
**Describe the bug**
Garbo keeps aborting due to Macro error when fighting Digitized KGEs (Specifically the romanticized ones in this case)

**Expected behavior**
Non-Abort to occur

**Session Log**
Visit to Dinseylandfill: Barf Mountain in progress...
(Romantic Monster window end counter expired)

[31479] Barf Mountain
Preference lastEncounter changed from angry tourist to Knob Goblin Embezzler
Encounter: Knob Goblin Embezzler
Preference _romanticFightsLeft changed from 2 to 1
Preference relayCounters changed from 31478:Romantic Monster window end loc=* type=wander:rparen.gif to
Preference relayCounters changed from to 31493:Romantic Monster window begin loc=*:lparen.gif
Preference relayCounters changed from 31493:Romantic Monster window begin loc=*:lparen.gif to 31493:Romantic Monster window begin loc=*:lparen.gif:31503:Romantic Monster window end loc=* type=wander:rparen.gif
Round 0: Flame6 wins initiative!
Round 1: Flame6 executes a macro!
KoLmafia thinks it is round 2 but KoL thinks it is round 1
You're on your own, partner. (Macro Aborted ("abort"))

**Additional context**
This has been happening for 4 months on my alt account and other accounts as well. Does not impact primary.

**Comment by horrible-little-slime** [comment]
#1824
