### ISSUE TITLE
[BUG] Expected a Digitized Knob Goblin Embezzler but encountered something else

### ISSUE THREAD

**Issue by Kulthozuer** [loathers/garbage-collector#1965]
**Describe the bug**
This is a bug report for a clannie who describes it as each day when they run garbo this happens after the embezzler fights. The script will expect to get a digitized embezzler and attempt to fight it in the Haunted Kitchen. It does encounter a KGE in the haunted kitchen but then states "Expected a digitized Knob Goblin Embezzler, but encountered something else." Kills the KGE to leave the combat and aborts.

**To Reproduce**
It seems to happen each day when garbo is run at the end of the embezzlers. There was another clan member who said the same thing has been happening.

**Session Log**
In the session log the Encounter that aborts garbo is found on Ln 15814 [2311] The Haunted Kitchen

[unusualscar_20240709.txt](https://github.com/user-attachments/files/16154720/unusualscar_20240709.txt)

![Captura_de_tela_2024-07-09_234634](https://github.com/loathers/garbage-collector/assets/151362077/8d3497b7-6c40-46bb-af40-3f5d612b9f48)

**Additional context**
The account in question does not loop and they state this has been happening for "Months" with no actual date. No new IoTM as this is an old account that a clannie is running who doesn't get new IoTM and just runs garbo for clan giveaways and such.

**Comment by kel4gt** [comment]
Adding the snapshot for reference: https://api.aventuristo.net/av-snapshot?u=unusualscar

**Comment by Tapionator** [comment]
Is your clanmate's "Enable auto-attack even against boss and special monsters" enabled? I ran into this bug multiple times in the recently and this resolved it.

**Comment by chocofungi** [comment]
i have also been experiencing this error for some time. i used to be able to hit "script" and it would run the fight for me but it's started saying "macro aborted" when i do that and i have to complete the fight by hand. auto attack isn't enabled, much less against special monsters

**Comment by Tapionator** [comment]
I'm confused, why don't you just enable the "Enable auto-attack even against boss and special monsters"? That should resolve the problem, it did for me!

**Comment by kel4gt** [comment]
That solved my alt's problem described at the original post too, TY so much guys <3
