### ISSUE TITLE
Unrecognized monster modifier: mimeo [BUG]

### ISSUE THREAD

**Issue by Tapionator** [loathers/garbage-collector#1969]
Occurred when facing purple KGE. Seems as though the monster modifier mimeo was incorrectly set within the script. Please see session log below for additional details:  Familiar request unsuccessful.
Putting on tiny stillsuit...
Equipment changed.
Saving outfit: Script Outfit 5
Outfit saved
Encounter: Knob Goblin Embezzler
Unrecognized monster modifier: mimeo
Encounter: Knob Goblin Embezzler
Unrecognized monster modifier: mimeo
Preference parkaMode changed from kachungasaur to dilophosaur
Your parka is now set to dilophosaur mode.
No spading data has been collected yet. Please try again later.
logPreferenceChange => false
Preference logPreferenceChange changed from true to false
CCS set to default
hpAutoRecoveryTarget => 0
mpAutoRecoveryTarget => 0
valueOfInventory => 2
choiceAdventure1108 => 1
choiceAdventure1468 => 4
choiceAdventure1472 => 4
choiceAdventure1116 => 0
Encounter: Knob Goblin Embezzler
Unrecognized monster modifier: mimeo
You fought 19 Knob Goblin Embezzler at the beginning of the day, and an additional 0 digitized Knob Goblin Embezzler throughout the day. Good work, probably!
Including this, you have fought 19 across all ascensions today
Extreme Items:
1 eldritch dough worth 799999 total
3 Volcoino worth 269100 total
1 psychoanalytic jar worth 103761 total
-24 flapper fly worth -118778 total
-3 Extrovermectin™ worth -89100 total
-1 superduperheated metal worth -69300 total
This run of garbo, across 21 turns you generated 1,243,401 meat, with -351,997 raw meat and 1,595,398 from items
So far today, across 21 turns you generated 1,243,401 meat, with -351,997 raw meat and 1,595,398 from items
Gerald wants 10 shots of peach schnapps, please!
Encounter: Knob Goblin Embezzler
Unrecognized monster modifier: mimeo

**Comment by Tapionator** [comment]
Seems to run fine after re-running. This only occurred on the first purple KGE.

**Comment by Tapionator** [comment]
Ah, sorry I saw the KolMafia changelog and see this issue was most likely addressed in that. Will re-open if error persists in newer version. Running Version 27998

**Comment by Tapionator** [comment]
Re-opening, updated KolMafia to newest version and error persisted on first purple KGE in second run. This time it was with the Obtuse Angel and said failure to equip familiar.

**Comment by capncastom** [comment]
+1 to purple embezzler probs.
Is this maybe missing the chained-combat handling magic sauce?

```
[954] The Briny Deeps
Preference lastEncounter changed from school of wizardfish to Knob Goblin Embezzler
Encounter: Knob Goblin Embezzler
Unrecognized monster modifier: mimeo
Round 0: capn castom wins initiative!
Preference cosmicBowlingBallReturnCombats changed from 18 to 17
Round 0: capn castom uses the pulled green taffy!
KoLmafia thinks it is round 1 but KoL thinks it is round 0
After Battle: Your toy train moves ahead to the Viewing Platform. As your train passes the viewing platform, the crowd shouts and cheers inspiring you!
Preference trainsetPosition changed from 674 to 675
After Battle: You gain 240 Fortitude
After Battle: You gain 263 Wizardliness
After Battle: You gain 207 Chutzpah

Preference _concoctionDatabaseRefreshes changed from 550 to 551
Preference customCombatScript changed from garbo to grimoire_macro
CCS set to grimoire_macro
hpAutoRecoveryTarget => 0
Preference hpAutoRecoveryTarget changed from 0.0 to 0
mpAutoRecoveryTarget => 0
Preference mpAutoRecoveryTarget changed from 0.0 to 0
Preference customCombatScript changed from grimoire_macro to garbo
CCS set to garbo
Autoattack is disabled.
Finished Backup
Encounter: Knob Goblin Embezzler
Unrecognized monster modifier: mimeo
Putting control the Robortender back into terrarium...
Taking Vicki the Mini Kiwi out of terrarium...
Familiar request unsuccessful.
Holding Kramco Sausage-o-Matic™...
Equipment changed.
Maximizer: Familiar Weight, -"equip Amulet of Perpetual Darkness", -"equip Buddy Bjorn", -"equip Spooky Putty ball", -"equip Spooky Putty leotard", -"equip Spooky Putty mitre", -"equip Spooky Putty snake", -"equip broken champagne bottle", -"equip dice-shaped backpack", -"equip papier-masque", -"equip papier-mitre", -"equip smoke ball", -"equip stinky fannypack", -"equip ¶5868", -"equip ¶5869", -"equip ¶5872", -buddy-bjorn, -crown-of-thrones, -off-hand, 100 "bonus pantogram pants", 104.9 "bonus Pantsgiving", 130.5 "bonus Snow Suit", 136.81 "bonus Crown of Thrones", 1588.85 "bonus lucky gold ring", 180 "bonus Mr. Screege's spectacles", 186.8 "bonus June cleaver", 220 "bonus Mr. Cheeng's spectacles", 287.51 "bonus bag of many confections", 302.81 "bonus can of mixed everything", 303.75 "bonus aviator goggles", 311 "bonus Daylight Shavings Helmet", 500 "bonus tiny stillsuit", 605.61 "bonus KoL Con 13 snowglobe", 71.69 "bonus rake", 71.69 "bonus tiny rake"
Maximizing...
24 combinations checked, best score 3,214.55
Putting on Daylight Shavings Helmet...
Equipment changed.
Wielding June cleaver...
Equipment changed.
Putting on Camp Scout backpack...
Equipment changed.
Putting on Stephen's lab coat...
Equipment changed.
Putting on Pantsgiving...
Equipment changed.
Putting on lucky gold ring...
Equipment changed.
Putting on Mr. Cheeng's spectacles...
Equipment changed.
Putting on Mr. Screege's spectacles...
Equipment changed.
Stealing tiny stillsuit from Wosevelt the Cornbeefadon...
Unequipping Wosevelt the Cornbeefadon...
Familiar request unsuccessful.
Putting on tiny stillsuit...
Equipment changed.
Saving outfit: Script Outfit 1
Outfit saved
Encounter: Knob Goblin Embezzler
Unrecognized monster modifier: mimeo
Encounter: Knob Goblin Embezzler
Unrecognized monster modifier: mimeo
Preference parkaMode changed from kachungasaur to dilophosaur
Your parka is now set to dilophosaur mode.
Sending kmail to Excavator...
sendmessage.php: redirected to a fight page.
JavaScript exception: KoLmafia error: sendmessage.php: redirected to a fight page.
at file:/Users/casey/Library/Application%20Support/KoLmafia/scripts/garbage-collector/garbo.js:50292 (main)
```

**Comment by Tapionator** [comment]
I think the main issue is that it is trying to use a modifier during the chained fight but it can't because you are already in the middle of a fight.

**Comment by Tapionator** [comment]
I think the main issue is that you are unable to equip the outfit customized for the KGE due to the fact you are already in the chained fight thus causing the script to break. Primary indicator of this being the "familiar request unsuccessful".

**Comment by VuvuzelaVirtuoso** [comment]
Also seeing this issue. Only posting the few that Occurred during the adventure beginning on line 44062 of the July 11th log where it hit
`Preference lastMacroError changed from Macro Aborted ("abort &quot;Macro for Powerful Glove expected Knob Goblin Embezzler but encountered something else.&quot;") to (Macro aborted.)`

For the July 14th log, it occurred during the adventure beginning on line 202012. As there were no error messages output into the session log and the error just occurred, I've attached images of the full GCLI output from the mafia client from when the error occurred. I was also seeing this on the last mafia version under slightly different circumstances (most likely just have been variance from garbo's farming patterns), but the consistency seems to be that no matter what the error occurs after `Unrecognized monster modifier: mimeo` and it's always on a chained ELP Mimeo encounter of an Embezzler. Interestingly, in the July 11th log, it actually did use ELP successfully another time without an abort (on a Mimic Egg, in that instance).

![image](https://github.com/user-attachments/assets/57d4ee73-ed79-4341-beab-0ba1071886c0)
![image](https://github.com/user-attachments/assets/2affeb7a-c628-40fb-b5c9-32a3e09d8987)



[vuvuzela_virtuoso_20240711.txt](https://github.com/user-attachments/files/16228209/vuvuzela_virtuoso_20240711.txt)

[vuvuzela_virtuoso_20240714.txt](https://github.com/user-attachments/files/16228217/vuvuzela_virtuoso_20240714.txt)

**Comment by gausie** [comment]
This is a kolmafia bug i think

**Comment by Tapionator** [comment]
Error is still persisting. Please see below. 
[1054] The Briny Deeps
Preference lastEncounter changed from school of wizardfish to Knob Goblin Embezzler
Encounter: Knob Goblin Embezzler
Unrecognized monster modifier: mimeo
Round 0: Tapion wins initiative!
Preference cosmicBowlingBallReturnCombats changed from 21 to 20
Round 0: Tapion uses the pulled green taffy!
KoLmafia thinks it is round 1 but KoL thinks it is round 0

Preference _concoctionDatabaseRefreshes changed from 536 to 537
Preference customCombatScript changed from garbo to grimoire_macro
CCS set to grimoire_macro
Encounter: Knob Goblin Embezzler
Unrecognized monster modifier: mimeo
hpAutoRecoveryTarget => 0
Preference hpAutoRecoveryTarget changed from 0.0 to 0
mpAutoRecoveryTarget => 0
Preference mpAutoRecoveryTarget changed from 0.0 to 0
Preference customCombatScript changed from grimoire_macro to garbo
CCS set to garbo
Autoattack is disabled.
Finished Backup
Putting Megaman the Robortender back into terrarium...
Taking Beat the Mini Kiwi out of terrarium...
Familiar request unsuccessful.
Taking off Buddy Bjorn...
Equipment changed.
Holding Kramco Sausage-o-Matic™...
Equipment changed.
Maximizer: Familiar Weight, -"equip Amulet of Perpetual Darkness", -"equip Buddy Bjorn", -"equip Spooky Putty ball", -"equip Spooky Putty leotard", -"equip Spooky Putty mitre", -"equip Spooky Putty snake", -"equip broken champagne bottle", -"equip dice-shaped backpack", -"equip papier-masque", -"equip papier-mitre", -"equip smoke ball", -"equip stinky fannypack", -"equip ¶5868", -"equip ¶5869", -"equip ¶5872", -buddy-bjorn, -crown-of-thrones, -off-hand, 136.81 "bonus Crown of Thrones", 155.82 "bonus Mayflower bouquet", 162 "bonus Snow Suit", 180 "bonus Mr. Screege's spectacles", 201.26 "bonus June cleaver", 2016.09 "bonus lucky gold ring", 220 "bonus Mr. Cheeng's spectacles", 296.54 "bonus can of mixed everything", 311 "bonus Daylight Shavings Helmet", 382.28 "bonus aviator goggles", 43.07 "bonus rake", 43.07 "bonus tiny rake", 500 "bonus tiny stillsuit", 6.25 "bonus Powerful Glove"
Maximizing...
24 combinations checked, best score 3,597.35
Putting on Daylight Shavings Helmet...
Equipment changed.
Wielding June cleaver...
Equipment changed.
Putting on Camp Scout backpack...
Equipment changed.
Putting on Stephen's lab coat...
Equipment changed.
Putting on Mr. Cheeng's spectacles...
Equipment changed.
Putting on Mr. Screege's spectacles...
Equipment changed.
Stealing tiny stillsuit from Hadolph the Cornbeefadon...
Unequipping Hadolph the Cornbeefadon...
Familiar request unsuccessful.
Putting on tiny stillsuit...
Equipment changed.
Saving outfit: Script Outfit 4
Outfit saved
Encounter: Knob Goblin Embezzler
Unrecognized monster modifier: mimeo
Encounter: Knob Goblin Embezzler
Unrecognized monster modifier: mimeo
Preference parkaMode changed from kachungasaur to dilophosaur
Your parka is now set to dilophosaur mode.
No spading data has been collected yet. Please try again later.
logPreferenceChange => false
Preference logPreferenceChange changed from true to false
CCS set to default
hpAutoRecoveryTarget => 0
mpAutoRecoveryTarget => 0
valueOfInventory => 2
choiceAdventure1108 => 1
choiceAdventure888 => 3
Encounter: Knob Goblin Embezzler
Unrecognized monster modifier: mimeo
You fought 22 Knob Goblin Embezzler at the beginning of the day, and an additional 0 digitized Knob Goblin Embezzler throughout the day. Good work, probably!
Including this, you have fought 22 across all ascensions today
Extreme Items:
3 eldritch ichor worth 540000 total
2 Volcoino worth 174000 total
3 pocket wish worth 134946 total
-1 Daily Affirmation: Always be Collecting worth -99000 total
-15 Special Seasoning worth -74048 total
-5 Ambitious Turkey worth -44775 total
This run of garbo, across 22 turns you generated 966,947 meat, with -503,007 raw meat and 1,469,954 from items
So far today, across 22 turns you generated 966,947 meat, with -503,007 raw meat and 1,469,954 from items
JavaScript exception: Failed to fully dress (expected: familiar Mini Kiwi)
