### ISSUE TITLE
[BUG] The last 5 FreeRunFights were not free!

### ISSUE THREAD

**Issue by giu-scopely** [loathers/garbage-collector#1979]
**Describe the bug**
So I have this happening to me every now and then on the last few days, garbo will spend some turns in the Shadow Rift then abort with this stack:

JavaScript exception: Error: The last 5 FreeRunFights were not free! (file:/E:/Loathing/Kol/scripts/garbage-collector/garbo.js#44053)
at file:/E:/Loathing/Kol/scripts/garbage-collector/garbo.js:44053 (f)
at file:/E:/Loathing/Kol/scripts/garbage-collector/garbo.js:45441 (freeFights)
at file:/E:/Loathing/Kol/scripts/garbage-collector/garbo.js:50272
at file:/E:/Loathing/Kol/scripts/garbage-collector/garbo.js:41522 (withClan)
at file:/E:/Loathing/Kol/scripts/garbage-collector/garbo.js:41516 (withVIPClan)
at file:/E:/Loathing/Kol/scripts/garbage-collector/garbo.js:50253
at file:/E:/Loathing/Kol/scripts/garbage-collector/garbo.js:41501 (withStash)
at file:/E:/Loathing/Kol/scripts/garbage-collector/garbo.js:50252 (main)

**To Reproduce**
I just ran garbo after doing my daily breakfast stuff.

**Expected behavior**
Some days it works completely and goes on just fine.

**Session Log**
Attach a full KoLMafia session log from the day you encountered the bug. Include details about when in the log the bug occurred to help developers rapidly find the error. Copy and paste any associated red text printed to the gCLI during this error.

[lacey_jones_20240723.txt](https://github.com/user-attachments/files/16347357/lacey_jones_20240723.txt)

**Additional context**
The error in the log has just happened for the first time at the end of the attached file.
Every time I get this error is an infinite loop, I run garbo again and it runs 5 turns and stop with the same error and so on.

**Comment by giu-scopely** [comment]
After reading through garbo.js I found a way to prevent it by removing the last element in the `freeFightSources` array, but some of that shadow rift free fights logic is doing something that shouldn't there.

**Comment by horrible-little-slime** [comment]
I notice that the preference `_shadowAffinityToday` doesn't appear to get adjusted at all during this time. Did you do something weird with your closed-circuit payphone? is it in the closet, for example?

**Comment by horrible-little-slime** [comment]
Upon reflection, I suspect the answer is that you
- own a closed-circuit payphone
- keep it in your closet or hagnks
- have `autoSatisfyWithCloset` or `autoSatisfyWithStorage` set to true, meaning that `availableAmount` will return `1` rather than `0`

My advice would be to either uncloset the phone (if you want it to be used) or turn off `autoSatisfyWithCloset` (if you don't)

**Comment by giu-scopely** [comment]
For sure I dont have the phone in my closet, just checked and its in my inventory, running this again today without commenting out the the shadow free fights to check what happens. Before running:
> prefref shadow
Name | Value | Default | Scope
-- | -- | -- | --
_shadowAffinityToday | false | false | user
_shadowBricksUsed | 0 | 0 | user
_shadowForestLooted | false | false | user
_shadowRiftCombats | 0 | 0 | user
considerShadowNoodles | false | false | user
lastShadowForgeUnlockAdventure | 292442 | -1 | user
shadowLabyrinthGoal | effects | browser | user
shadowRiftIngress | beanstalk |   | user
shadowRiftLastNC | 232 | N/A | user
shadowRiftTotalTurns | 243 | N/A | user
shadowsPoints | 0 | N/A | user

**Comment by giu-scopely** [comment]
Same thing, also checked and rufus quest says its finished, maybe that's the cause?

**Comment by horrible-little-slime** [comment]
> I guess that was it, but would be nice if the script checks for shadow affinity before trying to adventure in the shadow zones instead of relying on it being granted?

I think if more people were running into this I'd consider it worth it, but in general we rely on mafia preference tracking being correct, and it seems like your quest prefs were for some reason wrong. I'm going to close this for now, but if the issue pops up again we can spend more time on it.
