### ISSUE TITLE
[BUG] Garbo assumes Shocking Licks are available when none are.

### ISSUE THREAD

**Issue by Ignose** [loathers/garbage-collector#1992]
**Describe the bug**
The issue begins on the turn after 104838. Garbo believes, suddenly, a Shocking Lick charge is available and attempts to do wanderers to use this Shocking Lick. The script is rerun, and the issue occurs again on turn 104839 alongside a TTT pref issue which is later solved, with the next issue occurring at turn 104840; now in the Upper Chamber. The command 'Set ShockingLickCharges=0' is run on turn 104843 after which a script re-run immediately begins attempting to Shocking Lick through turns 104844 - 108445. Between 104845, Garbo is updated and re-run still creating the error.

This did not occur on my account, and I am uncertain how to reproduce given that preferences were set, checked, pref file checked and rechecked; but the issue persisted.

**Expected behavior**
When ShockingLickCharges = 0, Garbo should not attempt to Shocking Lick wander.
[ogl_20240806.txt](https://github.com/user-attachments/files/16517577/ogl_20240806.txt)

**Comment by horrible-little-slime** [comment]
> Preference shockingLickCharges changed from 1 to 0; kolfix auto

**Comment by Malibu-Stacey** [comment]
`set shockingLickCharges = 0` would've fixed your problem.

Mafia properties are case sensitive.
