### ISSUE TITLE
[BUG] JavaScript exception: Failed to fully dress (expected: familiar Obtuse Angel)

### ISSUE THREAD

**Issue by Tapionator** [loathers/garbage-collector#1997]
Garbo keeps breaking when fighting an Embezzler in the Briny Deeps. Similar to Mimeo bug though it it spitting an error regarding failure to dress familiar and is trying to equip my robort with a quake of arrows and then the macro is breaking during battle. 

[423] The Briny Deeps
Preference lastEncounter changed from school of wizardfish to Knob Goblin Embezzler
Encounter: Knob Goblin Embezzler
Round 0: tapion wins initiative!
Preference cosmicBowlingBallReturnCombats changed from 44 to 43
Round 0: tapion uses the pulled green taffy!
KoLmafia thinks it is round 1 but KoL thinks it is round 0

allowNonMoodBurning => false
Preference allowNonMoodBurning changed from true to false
Preference customCombatScript changed from garbo to grimoire_macro
CCS set to grimoire_macro
hpAutoRecoveryTarget => 0
Preference hpAutoRecoveryTarget changed from 0.0 to 0
mpAutoRecoveryTarget => 0
Preference mpAutoRecoveryTarget changed from 0.0 to 0
allowNonMoodBurning => true
Preference allowNonMoodBurning changed from false to true
Preference customCombatScript changed from grimoire_macro to garbo
CCS set to garbo
Autoattack is disabled.
Finished Backup
Encounter: Knob Goblin Embezzler
Putting Megaman the Robortender back into terrarium...
Taking Balliam the Urchin Urchin out of terrarium...
Familiar request unsuccessful.
amulet coin is better than (none). Switching items...
Putting on amulet coin...
Equipment changed.
Maximizer: -tie, meat, "equip Mer-kin gladiator mask", -"equip Amulet of Perpetual Darkness", -"equip Spooky Putty ball", -"equip Spooky Putty leotard", -"equip Spooky Putty mitre", -"equip Spooky Putty snake", -"equip broken champagne bottle", -"equip dice-shaped backpack", -"equip papier-masque", -"equip papier-mitre", -"equip smoke ball", -"equip stinky fannypack", -"equip ¶5868", -"equip ¶5869", -"equip ¶5872", -buddy-bjorn, -crown-of-thrones
Maximizing...
1440 combinations checked, best score 3,522.41
Holding latte lovers member's mug...
Equipment changed.
Putting on carpe...
Equipment changed.
Putting on amulet coin...
Equipment changed.
Saving outfit: Script Outfit 2
Outfit saved
Taking pills for Wednesday - Sneakisol
Encounter: Knob Goblin Embezzler
Encounter: Knob Goblin Embezzler
Running fight Macrometeorite
Preference nextAdventure changed from The Briny Deeps to Noob Cave
Putting Megaman the Robortender back into terrarium...
Taking Whis the Obtuse Angel out of terrarium...
Familiar request unsuccessful.
amulet coin is better than (none). Switching items...
Putting on amulet coin...
Equipment changed.
Taking off Buddy Bjorn...
Equipment changed.
Putting on Crown of Thrones...
Equipment changed.
Your Robortender can't wear a quake of arrows
Maximizer: -tie, 10.25 Meat Drop, -"equip Amulet of Perpetual Darkness", -"equip Buddy Bjorn", -"equip Spooky Putty ball", -"equip Spooky Putty leotard", -"equip Spooky Putty mitre", -"equip Spooky Putty snake", -"equip broken champagne bottle", -"equip cheap sunglasses", -"equip dice-shaped backpack", -"equip papier-masque", -"equip papier-mitre", -"equip smoke ball", -"equip stinky fannypack", -"equip ¶5868", -"equip ¶5869", -"equip ¶5872", -buddy-bjorn, -crown-of-thrones, -familiar, -hat, 100 "bonus pantogram pants", 180 "bonus Mr. Screege's spectacles", 207.78 "bonus June cleaver", 220 "bonus Mr. Cheeng's spectacles", 274.33 "bonus Crown of Thrones", 276.87 "bonus can of mixed everything", 305.36 "bonus lucky gold ring", 333.33 "bonus mafia thumb ring", 6.25 "bonus Powerful Glove"

**Comment by horrible-little-slime** [comment]
Post log

**Comment by Tapionator** [comment]
[tapion_20240811.txt](https://github.com/user-attachments/files/16577275/tapion_20240811.txt)

**Comment by Tapionator** [comment]
familiar Robortender (153 lbs)
> Running fight Backup

cast 1 Musk of the Moose
You acquire an effect: Musk of the Moose (10)

use 1 fishy pipe
You acquire an effect: Fishy (10)
Preference _fishyPipeUsed changed from false to true
Preference nextAdventure changed from VYKEA to The Briny Deeps

equip off-hand Roman Candelabra

equip hat Mer-kin gladiator mask

equip back Buddy Bjorn

equip familiar little bitty bathysphere
Maximizer: -tie, 10.25 Meat Drop, -"equip Amulet of Perpetual Darkness", -"equip Crown of Thrones", -"equip Spooky Putty ball", -"equip Spooky Putty leotard", -"equip Spooky Putty mitre", -"equip Spooky Putty snake", -"equip broken champagne bottle", -"equip cheap sunglasses", -"equip dice-shaped backpack", -"equip papier-masque", -"equip papier-mitre", -"equip smoke ball", -"equip stinky fannypack", -"equip ¶5868", -"equip ¶5869", -"equip ¶5872", -acc1, -back, -buddy-bjorn, -crown-of-thrones, -familiar, -hat, -off-hand, 100 "bonus pantogram pants", 180 "bonus Mr. Screege's spectacles", 207.78 "bonus June cleaver", 220 "bonus Mr. Cheeng's spectacles", 276.87 "bonus can of mixed everything", 277.48 "bonus Buddy Bjorn", 305.36 "bonus lucky gold ring", 333.33 "bonus mafia thumb ring", 6.25 "bonus Powerful Glove"

equip shirt Jurassic Parka

equip acc2 anemoney clip

equip acc3 incredibly dense meat gem
> Maximize: 10.25 Meat Drop,-tie

bjornify Pair of Ragged Claws (105 lbs)
> Now running Knob Goblin Embezzler fight: Backup. Stay tuned for details.
Preference lastAdventure changed from VYKEA to The Briny Deeps

[422] The Briny Deeps
Preference lastEncounter changed from Just Some Oak and Some Pine and a Handful of Norsemen to school of wizardfish
Encounter: school of wizardfish
Round 0: tapion wins initiative!
Round 0: tapion casts BACK-UP TO YOUR LAST ENEMY!
Round 1: your opponent becomes a Knob Goblin Embezzler!
Preference _backUpUses changed from 8 to 9
Round 1: tapion uses the pulled green taffy!
You acquire an item: envyfish egg
Round 2: Bonderson leaps out of the Buddy Bjorn and makes clackety-clack! noises as it chases your startled opponent around the battlefield.
Preference envyfishMonster changed from  to Knob Goblin Embezzler
Round 2: tapion casts RECALL FACTS: MONSTER HABITATS!
Preference _monsterHabitatsMonster changed from  to Knob Goblin Embezzler
Preference _monsterHabitatsFightsLeft changed from 0 to 5
Preference _monsterHabitatsRecalled changed from 0 to 1
Round 3: tapion casts RECALL FACTS: %PHYLUM CIRCADIAN RHYTHMS!
You acquire an effect: Recalling Circadian Rhythms (50)
Preference _circadianRhythmsPhylum changed from  to goblin
Preference _circadianRhythmsAdventures changed from 0 to 1
Preference _circadianRhythmsRecalled changed from false to true
Round 4: tapion casts BLOW THE PURPLE CANDLE!!
You acquire an effect: Everything Looks Purple (49)
Round 5: tapion casts SING ALONG!
Round 6: tapion casts BOWL STRAIGHT UP!
You acquire an effect: Cosmic Ball in the Air (45)
Round 7: Bonderson leaps out of the Buddy Bjorn and makes clackety-clack! noises as it chases your startled opponent around the battlefield.
Preference _cosmicBowlingSkillsUsed changed from 20 to 21
Preference cosmicBowlingBallReturnCombats changed from -1 to 44
Round 7: tapion casts EXTRACT!
You acquire an item: Source essence (2)
Round 8: tapion uses the seal tooth!
Round 9: Knob Goblin Embezzler takes 1 damage.
Round 9: Bonderson leaps out of the Buddy Bjorn and makes clackety-clack! noises as it chases your startled opponent around the battlefield.
Round 9: tapion uses the seal tooth!
Round 10: Knob Goblin Embezzler takes 1 damage.
You gain 68 Meat.
Round 10: tapion uses the seal tooth!
Round 11: Knob Goblin Embezzler takes 1 damage.
Round 11: tapion uses the seal tooth!
Round 12: Knob Goblin Embezzler takes 1 damage.
Round 12: tapion uses the seal tooth!
Round 13: Knob Goblin Embezzler takes 1 damage.
Round 13: Bonderson leaps out of the Buddy Bjorn and makes clackety-clack! noises as it chases your startled opponent around the battlefield.
Round 13: tapion uses the seal tooth!
Round 14: Knob Goblin Embezzler takes 1 damage.
Round 14: tapion uses the seal tooth!
Round 15: Knob Goblin Embezzler takes 1 damage.
Round 15: tapion uses the seal tooth!
Round 16: Knob Goblin Embezzler takes 1 damage.
Round 16: Bonderson leaps out of the Buddy Bjorn and makes clackety-clack! noises as it chases your startled opponent around the battlefield.
Round 16: tapion uses the seal tooth!
Round 17: Knob Goblin Embezzler takes 1 damage.
Round 17: Bonderson leaps out of the Buddy Bjorn and makes clackety-clack! noises as it chases your startled opponent around the battlefield.
Round 17: tapion uses the seal tooth!
Round 18: Knob Goblin Embezzler takes 1 damage.
Round 18: Bonderson leaps out of the Buddy Bjorn and makes clackety-clack! noises as it chases your startled opponent around the battlefield.
Round 18: tapion uses the seal tooth!
Round 19: Knob Goblin Embezzler takes 1 damage.
Round 19: Bonderson leaps out of the Buddy Bjorn and makes clackety-clack! noises as it chases your startled opponent around the battlefield.
Round 19: tapion uses the seal tooth!
Round 20: Knob Goblin Embezzler takes 1 damage.
Round 20: tapion uses the seal tooth!
Round 21: Knob Goblin Embezzler takes 1 damage.
Round 21: Bonderson leaps out of the Buddy Bjorn and makes clackety-clack! noises as it chases your startled opponent around the battlefield.
Round 21: tapion casts FURIOUS WALLOP!
Round 22: Knob Goblin Embezzler takes 1420 damage.
Round 22: tapion wins the fight!
Your familiar gains a pound: Megaman, the 10 lb. Robortender
After Battle: Bonderson surveys the scene from your back, and gains 1 Experience.
After Battle: Captain Megaman waves his hands at you until you notice the Meat he's found. (+30% Meat Drops)
After Battle: Megaman berates your fallen adversary for not tipping, and checks their pockets.
You gain 29451 Meat
After Battle: Some extra meat has appeared in your pouch when you weren't looking. Presumably Dark Belle's doing.
You gain 12 Meat.
After Battle: Although they won't admit it publicly, biologists agree that the Knob Goblin Embezzler secretes a natural antiantifreeze from its lungs to keep it cool during the hot summer months.
You acquire an effect: Antiantifrozen (10)
You acquire an item: meat stack
You acquire an item: meat stack
You acquire an item: meat stack
You acquire an item: meat stack
You acquire an item: Knob Goblin visor
You acquire an item: embezzler's oil
After Battle: Ah, a goblin! Your remember a neat fact about their sleep cycle. You'll probably sleep a bit better tonight.
You lose some of an effect: Recalling Circadian Rhythms (4)
After Battle: Megaman passes you a bowl of peanuts. Except instead of peanuts, it's candy.
You acquire an item: licorice boa
After Battle: You gain 27 Beefiness
After Battle: You gain 11 Mysteriousness
After Battle: You gain 12 Chutzpah
After Battle: After the battle, you settle down on a spot behind a suggestively-shaped piece of coral and let the leylines restore you.
You acquire an effect: Cartographically Charged (10)
You acquire an item: inflammable leaf
After Battle: You gain 1 Magicalness
Preference _boomBoxFights changed from 2 to 3
Preference _circadianRhythmsAdventures changed from 1 to 2
Preference familiarSweat changed from 719 to 720

[423] The Briny Deeps
Preference lastEncounter changed from school of wizardfish to Knob Goblin Embezzler
Encounter: Knob Goblin Embezzler
Round 0: tapion wins initiative!
Preference cosmicBowlingBallReturnCombats changed from 44 to 43
Round 0: tapion uses the pulled green taffy!
Preference allowNonMoodBurning changed from true to false
Preference customCombatScript changed from garbo to grimoire_macro
Preference hpAutoRecoveryTarget changed from 0.0 to 0
Preference mpAutoRecoveryTarget changed from 0.0 to 0
Preference allowNonMoodBurning changed from false to true
Preference customCombatScript changed from grimoire_macro to garbo
> Finished Backup
Encounter: Knob Goblin Embezzler

familiar Urchin Urchin (109 lbs)

equip familiar amulet coin
Maximizer: -tie, meat, "equip Mer-kin gladiator mask", -"equip Amulet of Perpetual Darkness", -"equip Spooky Putty ball", -"equip Spooky Putty leotard", -"equip Spooky Putty mitre", -"equip Spooky Putty snake", -"equip broken champagne bottle", -"equip dice-shaped backpack", -"equip papier-masque", -"equip papier-mitre", -"equip smoke ball", -"equip stinky fannypack", -"equip ¶5868", -"equip ¶5869", -"equip ¶5872", -buddy-bjorn, -crown-of-thrones

equip off-hand latte lovers member's mug

equip back carpe

equip familiar amulet coin

main.php?eowkeeper=1
Encounter: Knob Goblin Embezzler
Took choice 1395/3: unknown
choice.php?whichchoice=1395&option=3&pwd
Encounter: Knob Goblin Embezzler
> Running fight Macrometeorite
Preference nextAdventure changed from The Briny Deeps to Noob Cave

familiar Obtuse Angel (109 lbs)

equip familiar amulet coin
unequip container

equip hat Crown of Thrones
Maximizer: -tie, 10.25 Meat Drop, -"equip Amulet of Perpetual Darkness", -"equip Buddy Bjorn", -"equip Spooky Putty ball", -"equip Spooky Putty leotard", -"equip Spooky Putty mitre", -"equip Spooky Putty snake", -"equip broken champagne bottle", -"equip cheap sunglasses", -"equip dice-shaped backpack", -"equip papier-masque", -"equip papier-mitre", -"equip smoke ball", -"equip stinky fannypack", -"equip ¶5868", -"equip ¶5869", -"equip ¶5872", -buddy-bjorn, -crown-of-thrones, -familiar, -hat, 100 "bonus pantogram pants", 180 "bonus Mr. Screege's spectacles", 207.78 "bonus June cleaver", 220 "bonus Mr. Cheeng's spectacles", 274.33 "bonus Crown of Thrones", 276.87 "bonus can of mixed everything", 305.36 "bonus lucky gold ring", 333.33 "bonus mafia thumb ring", 6.25 "bonus Powerful Glove"

equip off-hand latte lovers member's mug

equip back carpe

equip acc2 wormwood wedding ring
> Maximize: 10.25 Meat Drop,-tie
Preference customCombatScript changed from garbo to default
Preference hpAutoRecoveryTarget changed from 0.0 to 1
Preference mpAutoRecoveryTarget changed from 0.0 to 0.6
Preference allowNonMoodBurning changed from true to false
Preference valueOfInventory changed from 2.0 to 2
Preference choiceAdventure1108 changed from 1 to 3
Preference choiceAdventure1387 changed from 2 to 3
Preference choiceAdventure1209 changed from 2 to 0
Preference choiceAdventure1214 changed from 1 to 0
Preference choiceAdventure1115 changed from 6 to 0
Encounter: Knob Goblin Embezzler
> You fought 17 Knob Goblin Embezzler at the beginning of the day, and an additional 0 digitized Knob Goblin Embezzler throughout the day. Good work, probably!
> Including this, you have fought 197 across all ascensions today
> Extreme Items:
> 2 Volcoino worth 149910 total
> 3 pocket wish worth 134730 total
> 1 cuppa Voraci tea worth 62907 total
> -1 spice melange worth -245675 total
> -4 Extrovermectin&trade; worth -112043 total
> -6 splendid martini worth -70200 total

**Comment by horrible-little-slime** [comment]
Looks redundant with #2000 , which better articulates the issue
