### ISSUE TITLE
[BUG] Garbo failing to diet, throwing Arithmetic Exception

### ISSUE THREAD

**Issue by Ignose** [loathers/garbage-collector#2004]
**Describe the bug**
`JavaScript exception: JavaException: java.lang.RuntimeException: java.lang.ArithmeticException: / by zero` is being thrown when running Garbo during the diet section.

**To Reproduce**
Run Garbo on KoLmafia-28012 with empty organs.

**Expected behavior**
Garbo should diet and run.

[seraphiii_20240813.txt](https://github.com/user-attachments/files/16599517/seraphiii_20240813.txt)

**Comment by Ignose** [comment]
Looks like this may be a mafia bug @gausie - `acquire 2 ambitious turkey` gives error:

`Unexpected error, debug log printed.`
[DEBUG_20240813.txt](https://github.com/user-attachments/files/16600776/DEBUG_20240813.txt)

Log attached.

**Comment by yendi** [comment]
Can confirm same issue. Script and Mafia updated to latest version.

[yendi_20240813.txt](https://github.com/user-attachments/files/16601025/yendi_20240813.txt)
