### ISSUE TITLE
[BUG] Not using resources to chain Mimes on second run (Fought 2 on second run total)

### ISSUE THREAD

**Issue by Tapionator** [loathers/garbage-collector#2014]
For some reason none of my copiers are being used on my second run with Garbo. Professor Calculator used 0 lectures, I have backup camera uses left, Roman candle was never used etc. I usually have enough copiers to fight 101 KGEs in the past (last run of garbo did this 2 days ago). Attached session of 2nd run only. 
[15AUG24 - Tapion - 2nd Run (Garbo).txt](https://github.com/user-attachments/files/16628519/15AUG24.-.Tapion.-.2nd.Run.Garbo.txt)

**Comment by Tapionator** [comment]
Command ran was garbo workshed="cmc"

**Comment by zarefore** [comment]
I started a discussion about this yesterday. Anecdotally it seemed like I used more of my copy resources today with the Cheerless Mime Executive in my locket and chateau painting—I assume the issue is that since the monster is not wishable or trivially summonable with a clover that if the chain gets broken it is more difficult than Embezzlers were to get started again and there isn't a fallback yet.

**Comment by Tapionator** [comment]
Thank you I just added one to my locket and Chateau. Hopefully this fixes the problem for me. Appreciate it always Zarefore.

**Comment by Tapionator** [comment]
Looks like that did the trick!

**Comment by zarefore** [comment]
Garbo folks, is it possible to add a check such that if a player doesn't have the CME in their locket the script will equip a locket before the first CME fax of the day? Or does adding monsters to lockets fall outside of the scope of the script?

**Comment by Tapionator** [comment]
I'm surprised it doesn't consider the fax and the mimic egg as a source. When mine failed it did 2 mimic eggs and then bailed despite having 7 more on the ready.

**Comment by chunkinaround** [comment]
I was not on a loop leg and it also skipped copying CMEs for me such that I only fought two on the day. only through 2 mimic eggs
[threebullethamburgler_20240823.txt](https://github.com/user-attachments/files/16732726/threebullethamburgler_20240823.txt)

**Comment by chunkinaround** [comment]
Important to note, this has also shown me that getting my preferences wiped the other day made me lose my garbo_VipClan, which I have no rectified, it was set to a clan with no furniture.
