### ISSUE TITLE
[BUG] Cheer Item Fix still showing values of Cheer based on books

### ISSUE THREAD

**Issue by Tapionator** [loathers/garbage-collector#2018]
[tapion_20240816.txt](https://github.com/user-attachments/files/16637149/tapion_20240816.txt)
Saw fix for Cheer to better calculate it's value since many of use cannot use it for the skill books. Looks like it did not take as this was the result of my first run today. 

> Extreme Items:
> 1218 crystalline cheer worth 3705156 total
> 32 Coinspiracy worth 406985 total
> 1 spice melange worth 234000 total
> -4 Extrovermectin&trade; worth -90000 total
> -16 flapper fly worth -79056 total
> -11 Sacramento wine worth -66914 total

Thanks for all of your hard work!!

**Comment by Rinn** [comment]
[It already doesn't consider the books](https://github.com/loathers/garbage-collector/blob/da8d0f8b7a23e569672c932c3577168aaff40ad8/packages/garbo-lib/src/value.ts#L205). The high value was due to the price of the outfit pieces which have since some down
