### ISSUE TITLE
[BUG] dyin' to mimes 2: the re-death of ivan garbovich

### ISSUE THREAD

**Issue by docrostov** [loathers/garbage-collector#2051]
**Describe the bug**
i've waited a few days to report this because i wanted to make sure it wasn't a one-off thing. but my garbo has started dying to mimes again after being perfectly fine for a bit after #2019 was resolved. it may be due to some restoration settings, but i believe garbo does actually set up mafia to restore, so i am kind of at a loss as to what's going on. log for today attached:

[Captain_Scotch_20240829.txt](https://github.com/user-attachments/files/16803832/Captain_Scotch_20240829.txt)

**To Reproduce**
not sure, really! it sounds like this is mostly resolved for most others. it seems to happen daily at a few fights through the lecture chain.

**Expected behavior**
do not die to the mimes yolo

**Session Log**
[Captain_Scotch_20240829.txt](https://github.com/user-attachments/files/16803832/Captain_Scotch_20240829.txt)

at the end, haven't run any turns since it died

**Additional context**
here is my account state:
- level 32
- 540 mus, 596 myst, 1033 mox
- AT in normal aftercore, with most things unlocked
- pretty high shiny but not using any stash items

**Comment by horrible-little-slime** [comment]
Looks like you aren't taking too many rounds to kill--most guys are going down in 1-2 saucegeysers--but your moxie is so high that their attack is just insane.

We arent' currently casting Ruthless Efficiency.

I think it would be worth creating a `copyTargetMood` or `bigScalerMood` that we run against mimes et al that includes things like Ruthless Efficiency, TT shells, and other stuff not worth having up for barf.

**Comment by docrostov** [comment]
that tracks; as i thought back i realized this behavior only started when i ascended into AT. i doubt we can really fit it in our macros, but maybe have something set that uses saucy salve once a fight if you a. have it and b. are using the prof as a familiar as well? it's basically free HP, since mimes can't attack the first time you use it. it broke on the 12th lecture, so it was actually pretty close today. it usually breaks about 10-12 lectures since i ascended.

**Comment by horrible-little-slime** [comment]
> that tracks; as i thought back i realized this behavior only started when i ascended into AT. i doubt we can really fit it in our macros, but maybe have something set that uses saucy salve once a fight if you a. have it and b. are using the prof as a familiar as well? it's basically free HP, since mimes can't attack the first time you use it. it broke on the 12th lecture, so it was actually pretty close today. it usually breaks in about 10-12 lectures since i ascended.

We don't need to key it off pocket prof, we're already building bespoke macros for the profchain

**Comment by dutchladymilk** [comment]
just adding on to the dying to mimes issue, I've also been dying to a mime once per day. Have updated mafia and garbo to their latest versions
[milk1234_20240901.txt](https://github.com/user-attachments/files/16829496/milk1234_20240901.txt)

**Comment by Malibu-Stacey** [comment]
Good news, no one will ever fight another cheerless mime executive ever again.
Bad news, now we're copying cockroaches which need shenanigans to have them show up with be gregarious/habitat monster (and thus switch to them with monster replacers).
