### ISSUE TITLE
[BUG] Garbo gets stuck on Make Mimic Eggs

### ISSUE THREAD

**Issue by Cerxi** [loathers/garbage-collector#2056]
**Describe the bug**
Whenever I run garbo it eventually gets stuck on Executing Wanderers/Make Mimic Eggs. Sometimes I can halt it and start it again and it will start working again, other times it won't.

**To Reproduce**
Run `garbo`, wait.

**Expected behavior**
Normal farming behavior.

**Session Log**
[gardenGnostic_20240831.txt](https://github.com/user-attachments/files/16826752/gardenGnostic_20240831.txt)
The bug occurs at the end of the session.
![image](https://github.com/user-attachments/assets/be70ecad-5b01-4add-82a8-48b48abbc775)

**Additional context**
Sorry I haven't figured out anything about it.

**Comment by horrible-little-slime** [comment]
`set _mimicEggsObtained = 11`, just a pref misalignment

**Comment by horrible-little-slime** [comment]
Huh, actually, I'm pretty confident the issue is that KGEguards aren't stocked in eggnet. Someone should get on that!

**Comment by Cerxi** [comment]
I see! I guess I'll get on that!
