### ISSUE TITLE
[BUG] Mayo Clinic swaps after full diet is completed 

### ISSUE THREAD

**Issue by Tapionator** [loathers/garbage-collector#2058]
When used with Asdon the Mayo Clinic was swapped in (to replace the Asdon) after the Full Diet was completed rendering it as not very useful unless manually using the workshed prior to starting garbo. See attached log for more information. 

Command: Garbo workshed="Portable Mayo Clinic"

[Tapion Log - Mayo Swap Issue.txt](https://github.com/user-attachments/files/16840858/Tapion.Log.-.Mayo.Swap.Issue.txt)

**Comment by horrible-little-slime** [comment]
That's not what the word "bug" means

**Comment by Tapionator** [comment]
Apologies, I will modify the request.

**Comment by Tapionator** [comment]
Changing to Feature Request.
