### ISSUE TITLE
[BUG] Pocket Wish usage prompted to restart Witchess chain continuously with Eldritch Attunement in effect when using Backup Camera

### ISSUE THREAD

**Issue by Tapionator** [loathers/garbage-collector#2094]
Garbo continuously will loop prompting to use a pocket wish when trying to chain Witchess pieces with the Backup Camera with Eldritch Attunement active. This can be resolved by forgetting Eldritch Attunement prior to beginning the backup camera chain. 

See session log attached (I manually remove Eldritch Attunement within the session here, not garbo). 

Thanks as always. 

[tapion_20240910.txt](https://github.com/user-attachments/files/16962497/tapion_20240910.txt)

**Comment by horrible-little-slime** [comment]
have you considered just pressing "no"

**Comment by Tapionator** [comment]
Yes, and then I have all my backup camera uses that go unused.

**Comment by Tapionator** [comment]
The fact the Eldritch tentacle occurs after every free fight causes it impossible to use the backup camera correctly. This then causes the backup camera chain resources to go unused entirely throughout the run.
