### ISSUE TITLE
[BUG] Hobo Monkey used over Kiwi Bird despite Kiwi Bird being of greater value

### ISSUE THREAD

**Issue by Tapionator** [loathers/garbage-collector#2095]
Hobo Monkey used over Mini Kiwi despite Mini Kiwi being of higher value per adv. My familiar is at 166 lbs due to soup (both the monkey and kiwi bird). Hobo Monkey has a 622% drop rate plus it's 75 meat per enemy. This results in the hobo monkey being valued at 1630 meat from abilities.  Mini Kiwi would beat this out with it's drops being 1500 (actually 1600 at the moment) and it's leprechaun skill of 517% (1300 approx versus garbo enemy) totaling 2800 per enemy from familiar abilities. 

Session Log attached.

[Flame6_20240911.txt](https://github.com/user-attachments/files/16970941/Flame6_20240911.txt)

**Comment by horrible-little-slime** [comment]
Should be resolved now, let me know if it isn't

**Comment by Tapionator** [comment]
Works great, thank you very much :)
