### ISSUE TITLE
[BUG] Garbo spamming `differentiableQuantity` 191 times per 'pre-fight', function is not cached and makes URL request every time

### ISSUE THREAD

**Issue by libraryaddict** [loathers/garbage-collector#2105]
**Describe the bug**

If you have a mimic egg in your inventory, garbo will spam the function `differentiableQuantity` https://github.com/loathers/libram/blob/main/src/resources/2024/ChestMimic.ts#L146 which will perform an URL request on mimic egg each time to determine what monster it is. 

Just checked and it's counted it a whooping 191 times. So that's 191 extra requests to the backend, which at 300ms each, is 57.3 seconds extra. Per "pre-fight" calculation.

This is an issue only when you have a mimic egg in inventory.

**To Reproduce**

1. Probably just have a mimic egg in inventory, and you're still in the free fight portion

**Expected behavior**

Calls once, or libram caches output. Maybe its a mafia feature to write to pref?

**Comment by horrible-little-slime** [comment]
It's gonna be mafia support

**Comment by horrible-little-slime** [comment]
is 191 from the initial copy-target fights, or from barf turns?

does this happen if you only have relevant mimic eggs in your inventory, or do you have at least 1 egg that garbo doesn't currently want to fight?

**Comment by libraryaddict** [comment]
> is 191 from the initial copy-target fights, or from barf turns?
> 
> does this happen if you only have relevant mimic eggs in your inventory, or do you have at least 1 egg that garbo doesn't currently want to fight?

Initial copy-target turns.

I assume the latter? Given that it only had witchess knight, and it fought the egg later.
