### ISSUE TITLE
[BUG] Backup Camera not being used 

### ISSUE THREAD

**Issue by Tapionator** [loathers/garbage-collector#2114]
Backup Camera is now no longer being used or attempting to be used. Unsure if this still relates to it not having a emergency chain starter in place. Would adding mimic eggs as a primary chain starter instead of an emergency one resolve this? See session attached. Thanks as always for your help with this. 
[tapion_20240916.txt](https://github.com/user-attachments/files/17011688/tapion_20240916.txt)

**Comment by horrible-little-slime** [comment]
drink 1 eldritch elixir
You gain 12 Adventures
You gain 732 Fortitude
You gain a Muscle point!
You gain 666 Wizardliness
You gain some Mysticality points!
You gain 999 Roguishness
You gain some Moxie points!
You acquire an effect: Eldritch Attunement (5)
You acquire an effect: Eldritch Concentration (30)
You gain 3 Drunkenness
You lose some of an effect: Ode to Booze (-3)
Preference _concoctionDatabaseRefreshes changed from 48 to 49

**Comment by Tapionator** [comment]
Ah crap sorry didn’t think I had used it. I’m still confused as to why the elixir cancels out using the camera with an emergency source in place and a macro that supports it. I will work on a fix and propose it at a later date.

**Comment by Tapionator** [comment]
Thanks again Neil. Appreciate the help and sorry for the multitude of suggestions.

**Comment by Tapionator** [comment]
Solution :D didn’t realize tentacles could not be used to backup to. 

Backup Camera Usage:

Problem: Backup camera is not being used with Eldritch Attunement active

Solution:
1. If Eldritch Attunement is active and BackupUses <11 and free run available or ELG is not an active effect, use TargetEnemy Chain starter (mimic egg, locket, etc), use free run (with spring shoes and/or familiar). 
2. Adventure at Shadow Rift, use BACKUP TO LAST ENEMY if last enemy was target until backups uses are = to 11. 

Shadow Rifts are nowander so there should be no issues with tentacles in this zone. I was not aware earlier that the tentacles prevent the use of the backup camera. 

Hopefully this is a good solution! Looking forward to the feedback!
