### ISSUE TITLE
[BUG] Holiday Wanderer Handling at Barf

### ISSUE THREAD

**Issue by VuvuzelaVirtuoso** [loathers/garbage-collector#2127]
**Describe the bug**
Garbo encounters holiday wanderers while in Barf Mountain and aborts.

```
Executing Barf Turn/Barf

Visit to Dinseylandfill: Barf Mountain in progress...

[1015] Barf Mountain
Preference lastEncounter changed from garbage tourist to El Novio Cadáver
Encounter: El Novio Cadáver
Preference relayCounters changed from 1018:Holiday Monster window end loc=* type=wander:rparen.gif to
Preference relayCounters changed from to 1039:Holiday Monster window begin loc=*:lparen.gif
Preference relayCounters changed from 1039:Holiday Monster window begin loc=*:lparen.gif to 1039:Holiday Monster window begin loc=*:lparen.gif:1049:Holiday Monster window end loc=* type=wander:rparen.gif
Round 0: vuvuzela virtuoso wins initiative!
Preference cosmicBowlingBallReturnCombats changed from 13 to 12
Round 1: Your toy train moves ahead to the Coal Hopper. Your train takes on coal to power the next stop.
Preference trainsetPosition changed from 914 to 915
Round 1: vuvuzela virtuoso executes a macro!
KoLmafia thinks it is round 2 but KoL thinks it is round 1
You're on your own, partner. (Macro Aborted ("abort"))
[Click here to continue in the relay browser.](https://github.com/loathers/garbage-collector/issues/main.php)
```

**To Reproduce**
Encounter holiday wanderer while barfing. (happened with Dia de Los Muertos and Boris, not with Pirate though).

**Expected behavior**
For wanderer to be dealt with in way that prevents abort.

**Session Log**
```
You're on your own, partner. (Macro Aborted ("abort"))
[Click here to continue in the relay browser.](https://github.com/loathers/garbage-collector/issues/main.php)
```
[vuvuzela_virtuoso_20240923.txt](https://github.com/user-attachments/files/17093888/vuvuzela_virtuoso_20240923.txt)

**Additional context**
None.

**Comment by horrible-little-slime** [comment]
@VuvuzelaVirtuoso did you recently acquire the Monster Manuel

**Comment by VuvuzelaVirtuoso** [comment]
Nope, had one since February 14th, 2023. I've played every day since the beginning of 2023 so I should've gotten factoids for holiday wanderers by now, and I've had no issues running scripts like garbo on previous holidays like FoB and Dia de Los Muertos Borrachos.

**Comment by horrible-little-slime** [comment]
Can you share your pirate day log?

**Comment by VuvuzelaVirtuoso** [comment]
Sure, that's attached here:

[vuvuzela_virtuoso_20240919.txt](https://github.com/user-attachments/files/17155980/vuvuzela_virtuoso_20240919.txt)

**Comment by VuvuzelaVirtuoso** [comment]
Also attaching my log from the last FoB where I was seeing the same issues as I ultimately had with the Cadavers.

[vuvuzela_virtuoso_20240811.txt](https://github.com/user-attachments/files/17155996/vuvuzela_virtuoso_20240811.txt)

**Comment by VuvuzelaVirtuoso** [comment]
And for excessiveness' sake, here's a lot from the FoB back in Feb where Garbo was just fine for me. (The one in May I was in long aftercore for, and didn't visit Barf)
[vuvuzela_virtuoso_20240201.txt](https://github.com/user-attachments/files/17156034/vuvuzela_virtuoso_20240201.txt)

**Comment by horrible-little-slime** [comment]
To whoever looks at this next:
[this](https://github.com/loathers/garbage-collector/commit/bf3b3eca1180824df31e94a01894a506dea7ca12) is the only commit I can see that happened between pirate day and el dia de los muertos that could affect it, which seems unlikely to matter given that the macros look basically the same:
![image](https://github.com/user-attachments/assets/4c01bc2e-44f4-4ef1-a930-da656c79bb2f)

The other difference I notice is that in a successful pirate combat we see
```
Round 0: vuvuzela virtuoso wins initiative!
Preference cosmicBowlingBallReturnCombats changed from 3 to 2
Round 0: vuvuzela virtuoso casts SING ALONG!
Round 1: Your toy train moves ahead to the Ore Hopper Feeder. Some ore pours of the feeder into the hopper of your train.
Preference trainsetPosition changed from 879 to 880
You acquire an item: cardboard ore
```
whereas in the unsuccessful cadaver combat we see
```
Round 0: vuvuzela virtuoso wins initiative!
Preference cosmicBowlingBallReturnCombats changed from 12 to 11
Round 1: Your toy train moves ahead to the Ore Hopper Feeder. Some ore pours of the feeder into the hopper of your train.
Preference trainsetPosition changed from 853 to 854
You acquire an item: bubblewrap ore
Round 1: vuvuzela virtuoso executes a macro!
```
so that suggests there could be an issue with autoattack against special monsters here. 

Mafia data suggests neither are bosses, the main difference I see is that cadavar is nocopy and pirate isn't.
