### ISSUE TITLE
[BUG] Garbo keeps trying to adventure in Gingerbread City

### ISSUE THREAD

**Issue by gumpy13** [loathers/garbage-collector#2129]
**Describe the bug**
When running garbo Gingerbread City turns seem to get miscounted.  I have to manually change the value of _gingerbreadCityTurns from 14 to 16 every day or garbo will attempt to adventure there infinitely.

**To Reproduce**
Run garbo

**Session Log**
allowNonMoodBurning => false
Preference allowNonMoodBurning changed from true to false
Preference customCombatScript changed from garbo to grimoire_macro
CCS set to grimoire_macro
hpAutoRecoveryTarget => 0
Preference hpAutoRecoveryTarget changed from 0.0 to 0
mpAutoRecoveryTarget => 0
Preference mpAutoRecoveryTarget changed from 0.0 to 0
allowNonMoodBurning => true
Preference allowNonMoodBurning changed from false to true
Preference customCombatScript changed from grimoire_macro to garbo
CCS set to garbo
Autoattack is disabled.
Putting on outfit: Script Outfit 0
Equipment changed.
Putting on outfit: Gingerbread Best
Preference _concoctionDatabaseRefreshes changed from 1098 to 1099
Equipment changed.

That area is not available.

**Comment by dutchladymilk** [comment]
having the same issue as gumpy13

**Comment by horrible-little-slime** [comment]
Seems like a prefs misalignment issue.

**Comment by gumpy13** [comment]
> Seems like a prefs misalignment issue.

How do I fix that?
