### ISSUE TITLE
[BUG] sandworms skipped, freekill sources ignored ?

### ISSUE THREAD

**Issue by capncastom** [loathers/garbage-collector#2138]
Hi!

Latest mafia / latest garbo

Ive noticed the past couple days, when running `garbo target="cockroach"` specifically, that garbo has been skipping sandworm kills and freekill uses.

not doing steely-eyed squint, 
jokester gun
shattering punches
batoomerang
shadow bricks, etc...

These resources also appear in tourguide, so mafia knows about them.

Fired up a 5 day-old version of garbo (thanks Tapion) and it immediately started fighting sandworms and using freekills.

a session log:

[capn_castom_20240928.txt](https://github.com/user-attachments/files/17175591/capn_castom_20240928.txt)

**Comment by Tapionator** [comment]
Newest version skips sandworm fights as well.

**Comment by capncastom** [comment]
r28073 is free-killing sandworms.
Thank you for your service!
