### ISSUE TITLE
[BUG] Not fighting Drunken Pygmies

### ISSUE THREAD

**Issue by Tapionator** [loathers/garbage-collector#2143]
In the past I used to face these during garbo runs all the time, now, I never fight them anymore during both y first and second run. Session attached. I do have all locations unlocked that are required to fight them and my free fight value is 3500. Unsure if this is a bug or something I have set wrong. 
[tapion_20240929.txt](https://github.com/user-attachments/files/17181317/tapion_20240929.txt)
Thanks!

**Comment by Tapionator** [comment]
Also, my ice house has a fluffy bunny. Was first thing I checked to see if that was causing the issue.

**Comment by horrible-little-slime** [comment]
The condition we use is this:
```
      get("questL11Worship") !== "unstarted" &&
      bowlOfScorpionsAvailable() &&
      !pygmySniffed()
        ? clamp(9 - get("_drunkPygmyBanishes"), 0, 9)
        : 0,
```
Looking through those, you should be fine. But
```
    {
      cost: () => {
        const banishers = pygmyBanishHandlers
          .filter(
            ({ skill, check, limit }) =>
              !skill || !have(skill) || (check && get(check) >= limit),
          )
          .map(({ item }) => item);
        return (
          retrievePrice($item`Bowl of Scorpions`) +
          sum(banishers, mallPrice) / 11
        );
      },
    },
    ```
    I don't know what your value of free fight is set to, but each of the banish items is around 10k these days, and it might just not be worth blowing 30k on 11 free fights.

**Comment by Tapionator** [comment]
The funny thing is... this worked after I bought a bunch of scorpion bowls... I wonder if the script doesn't auto buy them for you which is what was causing my issue?
