### ISSUE TITLE
[BUG]running infinite cicle by Executing Postcombat/Florist Plants Autoattack is disabled. Submitting option 1 for choice 720

### ISSUE THREAD

**Issue by exceliorxtreme** [loathers/garbage-collector#2162]
[extynt_20241101.txt](https://github.com/user-attachments/files/17605951/extynt_20241101.txt)
Executing Postcombat/Florist Plants
Autoattack is disabled.
Submitting option 1 for choice 720

those repeating  cicling infinite

how to change this state
thank you

somehow after visiting florist several time , this mesage disapears and all look back good

after a while happend again

most happend after in first aftercore day, mean after free king

**Comment by exceliorxtreme** [comment]
somehow after viviting florist several time , this mesage disapears and all look back good

**Comment by horrible-little-slime** [comment]
Please post a session log

**Comment by exceliorxtreme** [comment]
> Please post a session log

oki, i put, line in interest are like from 116411

**Comment by horrible-little-slime** [comment]
I'm seeing this ```
You are currently a member of Lost Generation
Preference _concoctionDatabaseRefreshes changed from 752 to 753
Preference _concoctionDatabaseRefreshes changed from 753 to 754
Preference floristFriarChecked changed from true to false
Preference floristFriarChecked changed from false to true
```
after practically every adventure, I think something is afoot with your mafia and you might be having frequent refreshes or errors updating your prefs file

**Comment by exceliorxtreme** [comment]
thank you

În lun., 4 nov. 2024 la 00:28, neil ***@***.***> a scris:
