### ISSUE TITLE
[BUG] takes excessive amounts of time trying to maximise something

### ISSUE THREAD

**Issue by chocofungi** [loathers/garbage-collector#2164]
**Describe the bug**
script is taking excessive amounts of time to run due to spending forever trying to maximise variables.
i've been running it for about 3 hours so far and it's only managed 400 turns. latest gcli output is "63820909 combinations checked, best score 663.64". top line is "10066917 combinations checked, best score 663.64" what is it gaining by spending so long with nothing to show for it?

**To Reproduce**
unsure. i just typed "garbo" and let it run. hours ago.

**Expected behavior**
that it doesn't take all day to run a few hundred turns?

**Session Log**
attached
[chocofungi_20241029.txt](https://github.com/user-attachments/files/17560915/chocofungi_20241029.txt)

**Additional context**
it's done it before recently, but not to this extent.

**Comment by horrible-little-slime** [comment]
consider setting your `maximizerCombinationLimit` in mafia to a smaller number than 63820909

**Comment by chocofungi** [comment]
mafia says "Unable to invoke maximizerCombinationLimit" can you suggest something else please?
