### ISSUE TITLE
Shadow Rift FreeRun abort error

### ISSUE THREAD

**Issue by SwimmingBear1** [loathers/garbage-collector#2174]
When I abort Garbo with esc, the "Kolmafia declares world peace" one, and then restart Garbo, it consistently throws me an error. Even though it's already done its Shadow Rift fights, it adventures 5 times in the rifts, spending adventures, before aborting, saying "The last five FreeRun fights weren't free!" I have solved this by running it again, and it works fine until the end of the day, even if I abort it again. 
So the error here is that it breaks and wastes 5 of my adventures. This has been a consistent problem for a while, across multiple of the latest KolMafia versions and Garbo updates.

**To Reproduce**
I just need to run garbo, abort it after it's done the shadow rift, and rerun it.

**Session Log**
[swimmingbear_20241130.txt](https://github.com/user-attachments/files/17966791/swimmingbear_20241130.txt)
The error occurs right at the end of the log.
"JavaScript exception: Error: The last 5 FreeRunFights were not free!"

**Additional context**
I think this has only happened pre-loop and it's not tied to IotMs (I've bought since I first started seeing this). I just got it where I ran Shadow Rift and then restarted KolMafia, but it usually happens when I just abort and then rerun Garbo.

**Comment by horrible-little-slime** [comment]
Your `encountersUntilSRChoice` seems to be set to an incorrect value; it seems to start the session at 6. It seems like the issue lies in the thing you've been doing in-between aborting and re-running:
```
Encounter: Mob Penguin steel driver
Preference _shadowRiftCombats changed from 22 to 23
Round 0: swimmingbear wins initiative!
Round 0: swimmingbear casts SHATTERING PUNCH!
Round 1: Your toy train moves ahead to the Water Tower, Fizzy. Carbonated water bubbles and fizzes as it fills your tanker car!
Preference trainsetPosition changed from 321 to 322
You acquire an effect: Carbonated (8)
Round 1: Hogdalena hops up and down excitedly, to indicate some additional meat she's found.
You gain 210 Meat.
Round 1: swimmingbear wins the fight!
After Battle: Hogdalena's candle glows brightly, casting fun spooky shadows everywhere.
After Battle: Hogdalena winks at you, which is one of the few things she can do that I don't have to qualify how it would be possible.
You gain 1,000 Meat
After Battle: Did you know that the Mob Penguin steel driver has a very particular flavor? Go ahead, give it a try!
You acquire an effect: Ooh, Sour! (10)
After Battle: Hogdalena does a spooky pirouette. How is a pirouette spooky? Well, remember in The Exorcist when the little girl's head turns all the way around?
You acquire an item: steel drivin' hammer
After Battle: Hogdalena smiles spookily. And spooks smilingly. (+44 Stats)
Preference _shatteringPunchUsed changed from 0 to 1
Preference nextAdventure changed from Barf Mountain to Shadow Rift (The Nearby Plains)
Preference encountersUntilSRChoice changed from 11 to 10
This combat did not cost a turn
```

It looks like mafia is errantly decrementing that pref because the downtown train fights don't have a zone.

**Comment by SwimmingBear1** [comment]
I've been busy with Crimbo instead of running garbo until now, but this issue has been happening on days that I haven't touched any weird zones, like today.

[swimmingbear_20250106.txt](https://github.com/user-attachments/files/18325009/swimmingbear_20250106.txt)

**Comment by spaghetti-squash** [comment]
The core issue is still the same, and seems to be a mafia one:
```
Round 4: suburban security civilian takes 2097 damage.
Round 4: suburban security civilian drops 9 attack power.
Round 4: suburban security civilian drops 10 defense.
Round 4: swimmingbear wins the fight!
You gain 232 Meat
After Battle: These things are heavier than they look!
After Battle: Magnolia flits around and points at cooking ingredients.
After Battle: You think you see a weird thing out of the corner of your eye, but it turns out to be nothing. Which is actually pretty weird, if you think about it, man.
Preference encountersUntilSRChoice changed from 1 to 0
Preference lastCopyableMonster changed from Eldritch Tentacle to suburban security civilian
This combat did not cost a turn
```
https://kolmafia.us/threads/trick-or-treat-causes-turns_spent-to-advance-in-wrong-zones.29354/
which recently got more attention here:
https://kolmafia.us/threads/cyberrealm-keycode-2025-item-of-the-year.30173/page-3#post-176163
idk why this is uniquely happening to you

interestingly, this isn't happening with any of the zoneless fights you're doing betwixt, but they're also not updating your last adventure: these are molehill mountain, the tentacle associated with molehill mountain, the glitch, the tentacle associated with the glitch, various CLL fights, nand their tentacles. I wonder if attunement is the issue?

**Comment by SwimmingBear1** [comment]
Alright, I can try it in a few days without attunement.

**Comment by spaghetti-squash** [comment]
https://github.com/kolmafia/kolmafia/pull/2727 alright this one's for you

**Comment by baralim** [comment]
Something similar seems to be happening to me, but it happens every time I run the script instead of just once on yesterday's build of Mafia.

[smugleafthesmug_20250213.txt](https://github.com/user-attachments/files/18792475/smugleafthesmug_20250213.txt)
