### ISSUE TITLE
[BUG] Autumn-Aton infinite loop on lack of zone access

### ISSUE THREAD

**Issue by yojimboslaw** [loathers/garbage-collector#2182]
[https://imgur.com/LsfLr1p](https://imgur.com/LsfLr1p)
Garbo is seeing that rock salt is very expensive and would like to get some, but can't because I don't have access to that version of the Orcish Frat House. I confirmed this item in particular was the cause by restarting kolmafia, listing rock salt at mall min with a 5/day limit, rerunning the script to update the value accordingly, and having it handle that choice adventure correctly.

The script reads like nonsense to me (I'm  sure it's well-written, but it's out of my wheelhouse), so I can't confirm whether or not this is a regexp that needs to be modified due to the recent KoL change to choice.php's html or whether there's just lacking logic for handling zone access, but one of those two seems to most likely be the issue.

**Comment by gausie** [comment]
Just a note that

> The script reads like nonsense to me (I'm sure it's well-written, but it's out of my wheelhouse)

is a really antisocial way of writing “I took a look to try to fix it but am afraid it is beyond my current skill level” or something.

**Comment by yojimboslaw** [comment]
Understood and sorry that it came off that way; I thought the second half
would make it clearly directed at me and not y'all.
