### ISSUE TITLE
[resource] doc bag

### ISSUE THREAD

**Issue by pstalcup** [loathers/garbage-collector#232]
If you have doc bag and not guzzlr, doing the quests can follow similar logic to guzzlr.
If you have doc bag and are in protracted aftercore, it can be more worth it than guzzlr (up to 50k per quest).
I am not sure if we really want to make automated decisions between the two, or have it be a property

**Comment by horrible-little-slime** [comment]
Should we burn all our freeruns on docbag quests when the combat rate of the zone is 100?

**Comment by docrostov** [comment]
closing because long aftercore flag needs to exist first, and more mafia support is -also- needed, which is actually a lot of things that have to happen before this has any chance of being implemented. sorry, long aftercore people (which is me)
