### ISSUE TITLE
[resource] utilization of "free buff" equipment

### ISSUE THREAD

**Issue by docrostov** [loathers/garbage-collector#399]
there are three main sources of "free buffs" in the game

- crazy horse (one buff every 5 turns, duration = 5)
- ittah bittah hookah (one buff every 6 turns, duration = 5)
- enhanced single receiver (one buff every turn, duration starts at 10 and ends at 2)

these are not actually as hard to value as it seems, and all of them are better on free fights than on non-free fights, because every buff you have at the end of free fights gets extended by 5 via PYEC. i have done spading on the value of various hookah effects ([located here](https://github.com/docrostov/KOLSpading/blob/master/KOL%20--%20Hookah%20Spading.ipynb)) and the value for hookah meat-wise is summarized as:

![image](https://user-images.githubusercontent.com/8014761/130166566-3efa5558-28cc-4b87-b7a5-06a50c4a88a3.png)

this means that the per-turn value of any free buff generator is:

> VALUE = (Activations Per Turn) * (Meat Buffs Per Activation) * (Turns of Buff * Meat of Buff Fights * Average Meat Buff Value)

so, for instance, crazy horses on free fights equate to

> FREE FIGHT VALUE = (1/5) * (4.74%) * ( (5 + 5) * (1025) * (46.3%) ) = 45 meat per fight

assuming you are fighting at least 10 embezzlers, have songboom, and are using a PYEC. that's really good! dark horse is worth 12 meat per fight, which is fine, but certainly under crazy horse. HOWEVER, on non-free fights, where you are facing normal barf fights, the equation becomes:

> FREE FIGHT VALUE = (1/5) * (4.74%) * ( (5) * (275) * (46.3%) ) = 6 meat per fight

anyway. the net result here is two things. first, these tools are way better on free fights than other fights, which is good, because most equipment is way worse on free fights! second, we can assign exact meat values to each of these, which we can use to feed into our outfit generator. this is a project i will probably take. here are some issues i need to think through

- how to deal with the Can Haz effects
- how to deal with passive damage in the context of our stasis code
- how to value the 500 meat cost of swapping from crazy horse to dark horse

anyway. this is a lil project for me. please post here if you think of other issues or other stuff to think about!

**Comment by horrible-little-slime** [comment]
We can estimate the number of free fights we'll get in the same way we estimate the number of embezzlers to help determine whether it beats the 500 meat cost of the switch.

**Comment by docrostov** [comment]
bumping this so i can continue to cry about how this is an annoying problem to solve

**Comment by docrostov** [comment]
closing as out of scope because past scotch was very ambitious about the time he would have to actually learn garbocode
