### ISSUE TITLE
Feature request: let us run garbo through the relay browser, with a checkbox for the ascend flag

### ISSUE THREAD

**Issue by horrible-little-slime** [loathers/garbage-collector#424]

**Comment by horrible-little-slime** [comment]
I think #710 has reawakened my interest in this; as we add more and more arguments to garbo, and increase customizability, adding the ability to run it through the relay browser will help more novice users (or, frankly, less novice users) keep track of running garbo in exactly the way that we want. As we add more and more userprefs--which we shouldn't let get _too_ bloaty--the relay interface will become more and more useful

**Comment by docrostov** [comment]
closing because sweaty bill is opening an issue in grimoire. TAKE THAT, KAS! THIS IS YOUR PROBLEM NOW! :)
