### ISSUE TITLE
Unsupported Choice Adventures

### ISSUE THREAD

**Issue by horrible-little-slime** [loathers/garbage-collector#509]
Currently supporting:
1427 (Guano Junction Cartography)
780 (Hidden Apartment scheduled nc)

**Comment by horrible-little-slime** [comment]
> 
> 
> #780 (Hidden Apartment scheduled nc)

Resolved

**Comment by horrible-little-slime** [comment]
923 doesn't belong on any forbid list, because wanderers override it and backups can still muscle through. Putting in PR for getting blackberry

**Comment by s-k-z** [comment]
1091 - The Floor Is Yours
https://github.com/Loathing-Associates-Scripting-Society/garbage-collector/pull/549

**Comment by docrostov** [comment]
1578 - hidden apartment building. should just skip adv (choice 6). doing a PR now

**Comment by docrostov** [comment]
877, 878, 879, 880, 876

these are the bedroom chain-to NCs; garbo would never have encountered them before but now encounters them because of the new freekill YR. (which is funny, that garbo will sometimes YR a monster with zero drops, but it's a dang free fight lol)

**Comment by docrostov** [comment]
> 877, 878, 879, 880, 876
> 
> these are the bedroom chain-to NCs; garbo would never have encountered them before but now encounters them because of the new freekill YR. (which is funny, that garbo will sometimes YR a monster with zero drops, but it's a dang free fight lol)

resolved in #1068

**Comment by docrostov** [comment]
![image](https://user-images.githubusercontent.com/8014761/209954202-fb1a6b2f-210d-409f-8936-b1e4695f55a4.png)
i am about to be in-run for a whole day but i will try to address this tomm

**Comment by docrostov** [comment]
![image](https://user-images.githubusercontent.com/8014761/228373504-c09bd0f8-b3ed-4749-ac8f-54475b45a6ff.png)
![image](https://user-images.githubusercontent.com/8014761/228373539-a441658e-b034-4400-977e-28b1e404c07e.png)

kind of surprised nobody's run into these before.

**Comment by horrible-little-slime** [comment]
This isn't really necessary for tracking just throw in a PR lads
