### ISSUE TITLE
thumb ring code is precariously close to causing an infinite loop

### ISSUE THREAD

**Issue by horrible-little-slime** [loathers/garbage-collector#636]

**Comment by Rinn** [comment]
it's also causing a bunch if circular imports!

**Comment by horrible-little-slime** [comment]
@Rinn are we comfortable marking this as closed by #1489 ?

**Comment by docrostov** [comment]
rinn confirmed this was effectively solved in #garbo-dev -- if this is a problem again we can make a new issue but the danger is (largely) behind us
