### ISSUE TITLE
[resource] Equip guzzlr pants on last turn to get more bux

### ISSUE THREAD

**Issue by Rinn** [loathers/garbage-collector#673]

**Comment by horrible-little-slime** [comment]
One thing that makes this more challenging is that our outfit and wanderer code don't currently talk to eachother. Adding it as a bonusEquip would be trivial were it not for that.

**Comment by pstalcup** [comment]
Do we know when we build our outfit if our next turn will be a wanderer? 
This will be complicated to solve and require restructuring of lots of code

**Comment by docrostov** [comment]
wanderer manager code refactor makes this easier for outfits to access; phred thinks this is a medium difficulty add (which probably means it's med-to-high) where you'd override the embezzler outfit in the event it's the last guzzlr turn. it is worth roughly 8-9k per quest if we do it. good luck!
