### ISSUE TITLE
[resource] eudoras & incredible self-esteem

### ISSUE THREAD

**Issue by docrostov** [loathers/garbage-collector#687]
currently garbo does not leverage the "incredible self-esteem" buff. it is a simple buff that, with no affirmation effects active, gives you 50 turns of a random affirmation. with one affirmation active, it gives +50 turns of that affirmation (and splits into 2 shots of +25 for each if you have 2 presently active and so on and so forth). if you have the skill, this is free value; there is a very simple way to support it, which is simply to add "cast this buff" into our buff casting at start-of-day. 

there is a more complicated use case here too tho. if you have the affirmation eudora, i -think- you may get this skill when you eudora swap. i cannot test this as i have it currently active in my run, but this is worth checking IMO because 50 free turns of +100% meat (which is what it would be if ABCs are profitable for garbo to buy, which has been the case (at least for me) for quite some time) is pretty phenomenal value and if we can wrangle eudoras such that users see this value that's pretty good.

just a thought, please feel free to rip apart my logic here friends.

**Comment by horrible-little-slime** [comment]
You do not get it if you swap. But yeah this is a good idea. I can add it to meatMood

**Comment by horrible-little-slime** [comment]
we now use incredible self esteem, but I'm not marking this resolved because we can shore up the math; if someone wants to do a more thorough and calculated implementation than #693, please feel free to do so

**Comment by Tokoeka** [comment]
Definitely feels like something that could get better implementation once/if #998 goes through?

**Comment by docrostov** [comment]
i don't think we are going to do a more thorough implementation at this point and what we have is fine lol
