### ISSUE TITLE
[resource] path-specific resource usage

### ISSUE THREAD

**Issue by docrostov** [loathers/garbage-collector#740]
to me this issue is less about the specifics and more about the framework of what "support for using resources in different flavors of aftercore" looks like to garbo. in my mind's eye what this looks like is similar to how libram does IOTM support; a folder called "aftercore" with, say, heavyRains.ts, awol.ts, etc. this will help garbo achieve maximum value for users in weird-path aftercores. some of these will be way harder to support than others, and i'm not entirely sure where in our code we'd call the path scripts, but i think this structure would help keep things organized and make sure that core garbo functions remain where they are while we add support for the edge cases. what do yall think.

**Comment by pstalcup** [comment]
Have you seen the new CS support in libram?

**Comment by horrible-little-slime** [comment]
It's not merged yet, but it will be soon:tm:

**Comment by docrostov** [comment]
this issue is too broad; to support a path, make a PR that outlines exact path support. goodbye old scotch.
