### ISSUE TITLE
[resource] Pizza Cube

### ISSUE THREAD

**Issue by pstalcup** [loathers/garbage-collector#749]
We are fighting a lot of embezzlers now, so if you have a pizza equipped it may be worth it to try to generate some of the high value pizzas. Additionally, you can offset the cost of the first pizza by the cost of a familiar jacks if you also include a familiar hatchling or equipment in the pizza
Here are some things that may be worth it:
-SINU
-LET*
-DOWN
-LOW*

Use of pizza would probably be a little complicated, but now that the diet code supports "buff" foods, we'd roughly have to do something like:
* compute the "best" version of each pizza, maybe with and without familiar equipment.
* from all of the possible pizzas, pick the best "familiar equipment" one, and subtract the price of familiar jacks
* submit these pizzas for consideration

**Comment by pstalcup** [comment]
One thing to note is this would fit in well if we allowed Garbo to swap work sheds

**Comment by horrible-little-slime** [comment]
After doing a bunch of math I'm pretty sure we've landed on the side of "this is extremely marginal and maybe worth it for one very weird account." I'm not going to close this issue, but I want this here for posterity in case someone's hunting down for a good thing to solve.

**Comment by docrostov** [comment]
closing as out of scope; if someone wants to make pizza support, be our guest, but it ain't gonna be us
