### ISSUE TITLE
[resource] Avatar of West of Loathing Extract Oil, Long Con and Meat Buff

### ISSUE THREAD

**Issue by Shanakor** [loathers/garbage-collector#973]
would be awesome if garbo could implement these 3 things.

I have no experience coding with garbo but this might be trivial to implement? (mallsearch the higher price of skin/unusual oil, autocast long con on the garbage tourist and autocast the 100% meat walk buff)

**Comment by docrostov** [comment]
closing this issue because we have implemented the minimum viable product (meat buff + long con). we are doing #1522 to add extract oil; it is possible this will lead to additional beat-ups, please tell us if that is the case (and you are still in AWoL, one point five years later)
